### ISSUE TITLE
Query not sent to server on IOS

### ISSUE THREAD

**Issue by agozie** [infitio/flutter_socket_io#1]
I ran the example on IOS with this URI  `const String URI = "http://192.168.1.100:7000?auth=12345";`. I got `socket.request._query` on the server to be `{ b64: '1', transport: 'polling' }` but on Android, I got `{ auth: '12345', EIO: '3', transport: 'polling' }` which is the expected data.

Secondly, how do I change transport from polling to websocket?

**Comment by tiholic** [comment]
@agozie please call `createInstance("http://192.168.1.100:7000", {"auth": "12345"})`

API Reference:
https://pub.dartlang.org/documentation/adhara_socket_io/latest/manager/SocketIOManager/createInstance.html

Transport will automatically upgrade from polling to websocket once the connection is established properly
