### ISSUE TITLE
Get responses after emitting events

### ISSUE THREAD

**Issue by JonathanJude** [infitio/flutter_socket_io#10]
How do one get responses from emitting events? I did

``` dynamic res = socket.emit("messages", [{"userId": "1223"}]); ```

But doesn't return anything. Any other way for this?

**Comment by tiholic** [comment]
@JonathanJude you can receive responses by listening to a specific event and emitting that from server.
`Ack` functionality is not been implemented yet and is in the roadmap.

Once Ack is implemented something like this can be done
`dynamic res = await socket.emit("messages", [{"userId": "1223"}]);`

**Comment by tiholic** [comment]
That's right. @JonathanJude

**Comment by mrleesin** [comment]
I'm also waiting for ack!!!

**Comment by tiholic** [comment]
Anyone interested in implementing `ack` can create a pull request

**Comment by tiholic** [comment]
Ack support is released in 0.3.1

**Comment by tiholic** [comment]
@JonathanJude @mrleesin
