### ISSUE TITLE
response 'on' > The Json Written Wrongly 

### ISSUE THREAD

**Issue by MohamedAbdelhadyPro** [infitio/flutter_socket_io#103]
response 'on' > The Json Written Wrongly 

code
```
    socket.on('activity', (response) {
      print(response);
    });
```

response
```
[
{activity:  Noura Hassan Join, created_at: 11:34:41}, 
{activity:  Join, created_at: 11:34:46}, 
{activity:  was left, created_at: 11:35:39},
 {activity: Join, created_at: 11:35:42},
 {activity: Noura Hassan was left, created_at: 11:37:36}
]
```

**Comment by tiholic** [comment]
@MohamedAbdelhadyPro what is the expected result here?

**Comment by RaistlinTAO** [comment]
For flutter env, this json string cannot be decoded since the common json_serializable plugin need the valid json string like this

{'activity':  'Noura Hassan Join', 'created_at': '11:34:41'}

unless its int ofc

**Comment by tiholic** [comment]
@RaistlinTAO JSON is converted into a `Map` in dart side. If you want the content to be available as json, please use `json.encode(data);`. For this you will need to `import 'dart:convert' show json;`
