### ISSUE TITLE
AndroidX compatibility issue after updating flutter

### ISSUE THREAD

**Issue by nareshimv** [infitio/flutter_socket_io#106]
After updating flutter version v1.9.1+hotfix.6 to v1.12.13+hotfix.5 . I'm not able run flutter project
**Stacktrace**

> Task :adhara_socket_io:verifyReleaseResources FAILED
:adhara_socket_io:verifyReleaseResources (Thread[Execution worker for ':' Thread 3,5,main]) completed. Took 1 mins 6.691 secs.
AAPT2 aapt2-3.4.0-5326820-osx Daemon #0: shutdown
         *********************************************************
WARNING: This version of package_info will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':adhara_socket_io:verifyReleaseResources'.
> 1 exception was raised by workers:
  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  /Users/SagarAdmin/Desktop/naresh/flutter/factoreal/build/adhara_socket_io/intermediates/res/merged/release/values/values.xml:236: error: resource android:attr/fontVariationSettings not found.
  /Users/SagarAdmin/Desktop/naresh/flutter/factoreal/build/adhara_socket_io/intermediates/res/merged/release/values/values.xml:237: error: resource android:attr/ttcIndex not found.
  error: failed linking references.
  

****
 After reverting back to previous flutter version 1.9.5 now i'm able to build apk

**Comment by DyaryRaoof** [comment]
same issue

**Comment by leviatan21** [comment]
Any news on this ?
Thanks

**Comment by leviatan21** [comment]
More than a month later and nothing yet.
Please respond:
Is this pkg abandoned ? or should we use another package

**Comment by tayseer9** [comment]
I fixed this error by changing compileSdkVersion from 27 to 28 in the build.gradle of the this dependency.

**Comment by Bricktheworld** [comment]
Yo can someone please fix this fucking package, its such a simple solution what @tayseer9 suggested and it works. please just fix it
