### ISSUE TITLE
build failed with adharasocketio after flutter upgrade, please help to solve this

### ISSUE THREAD

**Issue by handywijaya82** [infitio/flutter_socket_io#109]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'adhara_socket_io'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at 'C:\Users\acer\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\adhara_socket_io-0.4.1\android\local.properties'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

**Comment by Saifallak** [comment]
just add ANDROID_SDK_ROOT to system environments varriables. that equals to android.sdk.path

**Comment by handywijaya82** [comment]
> just add ANDROID_SDK_ROOT to system environments varriables. that equals to android.sdk.path

I already have android sdk root to system environment variable. problem only occur with adhara_socket_io only, if I remove this plugin from pubspec yaml project runs normally, and no error.

**Comment by Saifallak** [comment]
i know, that's a breaking change with latest flutter version, that you have to specify android_sdk_root in system environments

try adding "ANDROID_HOME" too

**Comment by singlakaran** [comment]
@Saifallak  i tried but still not working.

**Comment by Saifallak** [comment]
> @Saifallak i tried but still not working.

`flutter doctor -v` can you show me the output of this command ?

**Comment by singlakaran** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale en_IN)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Android Studio (version 3.6)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.

**Comment by Saifallak** [comment]
@singlakaran please run
`flutter doctor -v`
Not
`flutter doctor`

**Comment by singlakaran** [comment]
@Saifallak 
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale en_IN)
    • Flutter version 1.12.13+hotfix.8 at
      /home/karan/Downloads/flutter_linux_v1.9.1+hotfix.4-stable/flutter
    • Framework revision 0b8abb4724 (6 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/karan/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /snap/android-studio/84/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Android Studio (version 3.6)
    • Android Studio at /snap/android-studio/84/android-studio
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by Saifallak** [comment]
@singlakaran 
there is something wrong, you didn't put `ANDROID_HOME` and `ANDROID_SDK_ROOT` to PATH

if it's added , your `flutter doctor -v` android part should be like this

```
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\SDKs\android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\SDKs\android
    • Java binary at: C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
    • All Android licenses accepted.
```

you can see it can detect ANDROID_SDK_ROOT (2nd line) and ANDROID_HOME (5th line)

also run `flutter doctor --android-licenses` and accept the licenses, so you can get rid of that warning
