### ISSUE TITLE
io.socket.engineio.client.EngineIOException: websocket error

### ISSUE THREAD

**Issue by abdelrahman84** [infitio/flutter_socket_io#110]
Hello,

I have copied the exact code in the example. I tried both with emulator, and physical android device. I am trying to connect with socket.io of local server of node js.

The local host is : http://127.0.0.1:3000/

I have tried with the code sample, all possible scenarios for local host, like:

http://127.0.0.1:3000/

http://localhost:3000/

http://ipaddress:3000/

http://10.0.2.2:3000

Also, I tried a dummy socket:

wss://echo.websocket.org.

Still, I am getting the same error.

**To Reproduce**
1. Go to 'https://github.com/infitio/flutter_socket_io/blob/master/example/lib/main.dart
2. copy the code, and update pubsec.yaml.
3. flutter run.

**Device details:**
 - Device Type: [Android device, and emulator]
 - Model: [Huwaei Mate]
 - OS: [linux]

**Relevant Logs**
```
Add any relevant logs about the problem here.
```

**Comment by DMCHZP** [comment]
+1

**Comment by barees63** [comment]
I'm seeing the same behavior, every few seconds this error is thrown on both Emulator and physical Android devices.  No problems on iOS.

**Comment by DenisMrGnusa** [comment]
you can try this socket error: io.socket.engineio.client.EngineIOException: websocket

**Comment by tiholic** [comment]
Hope this issue is resolved.
Thanks @DenisMrGnusa 

Same is highlighted in [README](https://github.com/infitio/flutter_socket_io#android-support-for-sdk--27)
