### ISSUE TITLE
Build Apk fore release error

### ISSUE THREAD

**Issue by youraleangseng** [infitio/flutter_socket_io#111]
Exception
ProcessException: ProcessException: Permission denied
  ../adhara_socket_io-0.4.1/android/gradlew -I=/Users/../build/app -Pis-plugin=true -Ptarget-platform=android-arm,android-arm64,android-x64 assembleAarRelease

run: flutter build apk

<img width="724" alt="Screen Shot 2019-12-27 at 9 16 08 AM" src="https://user-images.githubusercontent.com/19517411/71497184-a14c8a80-2889-11ea-902c-0031348af70a.png">

```## flutter doctor

```
[✓] Flutter (Channel unknown, v1.12.13+hotfix.5, on Mac OS X 10.15.1 19B88, locale en-KH)
    • Flutter version 1.12.13+hotfix.5 
    • Framework revision 27321ebbad (2 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/youradev/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.9.0.beta.2

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • SM A505F • R58M31DT2QJ • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by DyaryRaoof** [comment]
having the same issue

**Comment by NarHakobyan** [comment]
any updates?

**Comment by gustavo-perini** [comment]
Same issue here

**Comment by NarHakobyan** [comment]
@gustavo-perini you can use my fork, It's working nice

**Comment by tiholic** [comment]
@youraleangseng please check in the latest release. Compile SDK version is upgraded and should be working fine.

**Comment by youraleangseng** [comment]
thank
