### ISSUE TITLE
Cant receive Packets with a AckCallback

### ISSUE THREAD

**Issue by CodeStrings** [infitio/flutter_socket_io#114]
**Description**
Packets that are send with a AckCallback are not accesible trough socket.on.

**To Reproduce**
1. Send a Packet with a Callback to the Client
2. Register with socket.on
3. Send Packet without Callback and it will work fine

**Expected behavior**
Execute .on and have a way to send back a result for the callback.

**Comment by CodeStrings** [comment]
Digging further it seems like it is just because of the length of the message. Whats the limit?

**Comment by tiholic** [comment]
@CodeStrings there is no length restrictions from this library. If you could share further information on this, it would be helpful.
