### ISSUE TITLE
json not received while any string received 

### ISSUE THREAD

**Issue by hatemragab** [infitio/flutter_socket_io#116]
while emit event from server 
if data is json format not received if any string data will received

**Comment by tiholic** [comment]
@hatemragab Isn't your use-case covered in the example? did you try running the example?

**Comment by hatemragab** [comment]
Yeah

**Comment by tiholic** [comment]
Can you share any code snippet? I will try it right away.

**Comment by tiholic** [comment]
@hatemragab v1.0.0 adds enhanced support for data encoding/decoding. Please try and re-open this issue if not resolved with example data your server is trying to send back. We can ensure it works by adding similar data structure to integration tests.
