### ISSUE TITLE
Error running pod install

### ISSUE THREAD

**Issue by srcker** [infitio/flutter_socket_io#117]
CDN: trunk URL couldn't be downloaded:
    https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/6/2/4/Socket.
    IO-Client-Swift/8.3.0/Socket.IO-Client-Swift.podspec.json, error: Failed to
    open TCP connection to raw.githubusercontent.com:443 (Connection refused -
    connect(2) for "raw.githubusercontent.com" port 443)

**Comment by tiholic** [comment]
@srcker seems to be an issue with your network/SSL
