### ISSUE TITLE
EngineIOException: websocket error

### ISSUE THREAD

**Issue by tazik561** [infitio/flutter_socket_io#118]
Accoeding this  structure i write this code :
https://pub.dev/packages/adhara_socket_io

```
 @override
  void initState() {
    super.initState();
    manager = SocketIOManager();
    initSocket();
  }

  initSocket() async {
    SocketIO socket =
        await manager.createInstance(SocketOptions('https://socket.******.ir'));
    socket.onConnect((data) {
      debugPrint("connected...");
      debugPrint(data);
    });
    socket.onConnectError((er) {
      debugPrint('onConnectError: $er');
    });
    socket.onConnectTimeout((er) {
      debugPrint('onConnectTimeout: $er');
    });
    socket.onError((er) {
      debugPrint('onError: $er');
    });
    socket.onDisconnect((er) {
      debugPrint('onDisconnect: $er');
    });
    socket.connect();
  }
```
now when i run application on emulator i got this error:
Syncing files to device Android SDK built for x86...
```
I/flutter ( 6791): onConnectError: io.socket.engineio.client.EngineIOException: websocket error
I/flutter ( 6791): onConnectError: io.socket.engineio.client.EngineIOException: websocket error
I/flutter ( 6791): onConnectError: io.socket.engineio.client.EngineIOException: websocket error
I/flutter ( 6791): onConnectError: io.socket.engineio.client.EngineIOException: websocket error
I/flutter ( 6791): onConnectError: io.socket.engineio.client.EngineIOException: websocket error
```

I also added add android:useCleartextTraffic="true" inside the application tag of AndroidManifest.xml.

For sure that socket server works correctly i am using socket.io tester chrome extention and this is it's results:

http://pasteall.org/pic/show.php?id=63d12d5a5fa19cd8b640182d3df9d37f

As you can see i send a message on test event and i received those message so the server works correctly.

What is the problem?

**Comment by misaelriojasftf** [comment]
Have you tested that connection? I've implemented without issues

**Comment by DenisMrGnusa** [comment]
https://github.com/infitio/flutter_socket_io/issues/42#issuecomment-513459096
