### ISSUE TITLE
getting data from socket when app is in background ios

### ISSUE THREAD

**Issue by yase-hesham** [infitio/flutter_socket_io#119]
is there any permissions in need to app to info.plist to continue receiving data from socket when app is in backgroud (IOS) ?

**Comment by misaelriojasftf** [comment]
have you tried?
```
<dict>
	<key>NSAllowsArbitraryLoads</key>
	<true/>
</dict>
```

**Comment by tiholic** [comment]
@yase-hesham running in background is bit of a task.

You could configure a background service on both android and iOS side which could call dart code via method channels, which then could start interacting with sockets.

Here is an official link from flutter on how to achieve that:
https://flutter.dev/docs/development/packages-and-plugins/background-processes
