### ISSUE TITLE
Socket.io cannot connect to server

### ISSUE THREAD

**Issue by patrickianco** [infitio/flutter_socket_io#12]
**Describe the bug**
I tried connecting to my socket.io using the example code and trying to connect to my local socket.io server. But it doesn't connect and when I enable the onConnectError listener I get the following error
`onConnectErrorio.socket.engineio.client.EngineIOException: xhr poll error`

**Expected behavior**
The app should be able to connect to the socket after a button click.

**Device details:**
 - Device: Asus Zenfone 4
 - OS: Android 8.1

**Comment by tiholic** [comment]
@patrickianco can you check if your server IP is configured correctly in the app?

**Comment by tiholic** [comment]
Yes, you will have to update the `URI` variable in `example/lib/main.dart#7` with your machine's IP address where you are running the socket.io-server

**Comment by patrickianco** [comment]
I have found the solution to my problem. In the socket server I have to enable the polling in the transports configuration. Apparently, Flutter apps communicate via polling rather than websockets so if you enable websockets on your socket server it will cause the error

**Comment by Troverun** [comment]
I hava  close  the  websockets ,     but i get  the exception   " I/flutter ( 4615): io.socket.engineio.client.EngineIOException: xhr poll error"  yet

**Comment by tiholic** [comment]
@Troverun are you facing the issue on iOS or Android?

**Comment by theromie** [comment]
Even i am facing same error on android where my Phone is connect to same wifi where i am running my server application

> io.socket.engineio.client.EngineIOException: xhr poll error

**Comment by tiholic** [comment]
@theromie @Troverun 
This could probably help https://github.com/infitio/flutter_socket_io#android-support-for-sdk--27

**Comment by tiholic** [comment]
@patrickianco Check the latest release. Using the new SocketOptions you can pass 
`transports: [Transports.WEB_SOCKET, Transports.POLLING]` in the order of preference.

**Comment by DenisMrGnusa** [comment]
you can try 
https://github.com/infitio/flutter_socket_io/issues/42#issuecomment-513459096
