### ISSUE TITLE
Execution failed for task ':adhara_socket_io:verifyReleaseResources'.

### ISSUE THREAD

**Issue by naveen-krishna** [infitio/flutter_socket_io#121]
**Describe the bug**
Build failed with an exception, when I tried to build release apk.

**Have you tried reproducing the issue with example available in this repo?**
Yes, same error. 

**To Reproduce**
1. flutter build appbundle 
2. flutter build apk

**Expected behavior**
build a release apk

**Relevant Logs**

> naveens-MacBook-Pro:kitchen naveen$ flutter build appbundle
> Removed unused resources: Binary resource data reduced from 36KB to 22KB: Removed 38%
> Running Gradle task 'bundleRelease'...                                  
> Running Gradle task 'bundleRelease'... Done                        11.2s
> ✓ Built build/app/outputs/bundle/release/app-release.aab (16.2MB).
> naveens-MacBook-Pro:kitchen naveen$ flutter build apk --split-per-abi

                                                                        
```
FAILURE: Build failed with an exception.



* What went wrong:

Execution failed for task ':adhara_socket_io:verifyReleaseResources'.

> 1 exception was raised by workers:

  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed

  /Users/naveen/Downloads/flutter_socket_io/example/build/adhara_socket_io/intermediates/res/merged/release/values/values.xml:236: error: resource android:attr/fontVariationSettings not found.

  /Users/naveen/Downloads/flutter_socket_io/example/build/adhara_socket_io/intermediates/res/merged/release/values/values.xml:237: error: resource android:attr/ttcIndex not found.

  error: failed linking references.







* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.



* Get more help at https://help.gradle.org



BUILD FAILED in 1s
Running Gradle task 'assembleRelease'...                            2.5s
Gradle task assembleRelease failed with exit code 1
Process finished with exit code 1
```

**Comment by KVGarg** [comment]
Hey! I just resolved this issue in my flutter project by changing the `compileSdkVersion` to 29
The error is raised because in SdkVersion 28 some new properties were added i.e. `fontVariationSetting` and `ttcIndex`. So, to resolve this issue we just need to change `compileSdkVersion` from 27 -> 28

**Comment by KVGarg** [comment]
Hey! The issue still needs to be resolved in this plugin. Th plugin should be made compatible to support sdk>=28 too. If not made, the error will still persist and the developer will have to separately change this plugin settings to make it compatible with their application.
Should I create a PR to solve this issue?

**Comment by tiholic** [comment]
@KVGarg released with https://github.com/infitio/flutter_socket_io/pull/120
