### ISSUE TITLE
[MISSING FEATURE] secure SocketOption parameter gone in latest version

### ISSUE THREAD

**Issue by angelhdz** [infitio/flutter_socket_io#122]
secure SocketOption parameter gone in the latest version. We can not connect via HTTPS.

On the Javascript client we can connect with the SSL certificate perfectly via https://address:port, that means both the JS client and the NodeJS server are working fine.

Error:

I/flutter ( 8007): io.socket.engineio.client.EngineIOException: websocket error

**Comment by husmen73** [comment]
We are using with SSL Socket Server URL like https://socket.server.com

**Comment by angelhdz** [comment]
> We are using with SSL Socket Server URL like https://socket.server.com

Thank you for replying.  Can you help me understand why can't I , and another mate, connect via HTTPS to a nodeJS server in a Flutter app? Is it a restriction of the Android Emulator?

**Comment by mawippel** [comment]
I'm having the same issue @angelhdz. I can't connect to a HTTPS NodeJs server through my Flutter App.

`I/flutter ( 7132): io.socket.engineio.client.EngineIOException: websocket error`

**Comment by husmen73** [comment]
If you're using nginx please check your config.

My config like that:

`location / {
            proxy_set_header Host             $host;
            proxy_set_header X-Real-IP        $remote_addr;
            proxy_set_header X-Forwarded-For  $proxy_add_x_forwarded_for;
            proxy_pass         http://localhost:10001;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_http_version 1.1;
        }
`

**Comment by mawippel** [comment]
I'm not using NGINX. My socket is NodeJS application using Socket.io, deployed on Azure Web App.
I think that's there's a problem with HTTPS connections.

**Comment by mawippel** [comment]
I was able to make it work deploying my socket application on an Azure VM, exposing the port 80 for HTTP connections. Probably Azure Web App has a security layer that was causing the connection error.
I suspect that the error that i had before was during the handshake phase.

**Comment by angelhdz** [comment]
> I was able to make it work deploying my socket application on an Azure VM, exposing the port 80 for HTTP connections. Probably Azure Web App has a security layer that was causing the connection error.
> I suspect that the error that i had before was during the handshake phase.

My mate solved it by making a pipe that connected both http and https conecctions in NodeJS. I haven't tried it yet, but I guess it should work for me as well.
