### ISSUE TITLE
Token is not working with Socket

### ISSUE THREAD

**Issue by vpaul9678** [infitio/flutter_socket_io#126]
It works well when I am connecting the socket to the server without token.
But it generates an error when i am using socket with token.

Here is the code that integrated when I am using token.

SocketOptions getSocketOptions(){
return SocketOptions(URI,
      nameSpace: "/",
      query: {
        "my_id": id,
        "auth": authToken //.substring(4),
      },
      enableLogging: true,
      transports: [Transports.WEB_SOCKET]// Transports.POLLING]
    );
}
SocketIO socket = await socketIOManager.createInstance(getSocketOptions());

socket.onConnect((data) {.......} //1
socket.onConnect((data) {.....}  //2
socket.onReconnecting((data) {...} //3
socket.on(topicName, (data) {......}  //4

Error
1,2,3 is in working and
 4 is not working

**Comment by tiholic** [comment]
@vpaul9678 Hopefully https://github.com/infitio/flutter_socket_io/pull/128 resolves this issue

**Comment by vpaul9678** [comment]
thank you
