### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by Microinstance** [infitio/flutter_socket_io#127]
* What went wrong:

Execution failed for task ':adhara_socket_io:verifyReleaseResources'.

> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade

   > Android resource linking failed

     C:\Users\Microinstance\.gradle\caches\transforms-2\files-2.1\bc3621e68f8e89178ad8f39e449bedd9\core-1.1.0\res\values\values.xml:142:5-173:25: AAPT: error: resource android:attr/fontVariationSettings not found.

     C:\Users\Microinstance\.gradle\caches\transforms-2\files-2.1\bc3621e68f8e89178ad8f39e449bedd9\core-1.1.0\res\values\values.xml:142:5-173:25: AAPT: error: resource android:attr/ttcIndex not found.

**Comment by disenyang** [comment]
How to resolve?

**Comment by tiholic** [comment]
@Microinstance @disenyang this only on windows or MacOS too?

**Comment by Saifallak** [comment]
this should be fixed in #120 too.

**Comment by tiholic** [comment]
@Microinstance @disenyang seems like this issue is not reproducible with latest versions. Feel free to re-open if required.
