### ISSUE TITLE
can't connect to netty-socketio server

### ISSUE THREAD

**Issue by stoneLee81** [infitio/flutter_socket_io#129]
netty-socketio server: 1.7.18
Flutter 1.12.13+hotfix.9
Dart 2.7.2
adhara_socket_io: ^0.4.2

I use adhara to connect to my nett-socketio IM server, but it failed.
demo code like this:
String urladdr = "http://192.168.122.96:15327/im/agent";

    SocketIOManager manager = SocketIOManager();
		SocketIO socket = await manager.createInstance(
      SocketOptions(
        urladdr,
        nameSpace: "/socket.io",
        enableLogging: true,
      transports: [Transports.WEB_SOCKET/*, Transports.POLLING*/]
    ));       //TODO change the port  accordingly
    socket.connect();

		socket.onConnect((data){
		  print("connected...");
		  print(data);
		  // socket.emit("message", ["Hello world!"]);
		});
		socket.on("news", (data){   //sample event
		  print("news");
		  print(data);
		});

log is as below:
W/ter_module.hos(31849): Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (greylist,core-platform-api, reflection, allowed)
D/Adhara:Socket(31849): registering::connect
D/Adhara:Socket(31849): registering::news
I/flutter (31849): [2020-05-27 12:34:57.54] Level.debug websocket_interface.dart:94 ::: Closed [500, HandshakeException: Connection terminated during handshake]!
I/flutter (31849): [2020-05-27 12:34:57.62] Level.debug websocket_interface.dart:160 ::: WebSocket wss://webrtcgw.tomatotrip.com:9060 closed
I/flutter (31849): [2020-05-27 12:34:57.69] Level.debug sip_ua_helper.dart:158 ::: disconnected => Code: [500], Cause: error, Reason: HandshakeException: Connection terminated during handshake
I/flutter (31849): [2020-05-27 12:34:57.77] Level.debug transport.dart:206 ::: reconnection attempt: 1. next connection attempt in 2 seconds
E/chromium(31849): [ERROR:aw_browser_terminator.cc(125)] Renderer process (32065) crash detected (code -1).
I/flutter (31849): [2020-05-27 12:34:59.89] Level.debug websocket_interface.dart:94 ::: Closed [500, HandshakeException: Connection terminated during handshake]!

**Comment by tiholic** [comment]
@stoneLee81 I am unable to connect to the URL mentioned from browser. Tried this. Can you confirm if your server is accepting connections?

```js
ws = new WebSocket("ws://192.168.122.96:15327/im/agent/socket.io/");
ws.onmessage = function (e) { console.log(e.data); };
ws.onopen = function() { ws.send("SomeMessage"); }
```

**Comment by stoneLee81** [comment]
https://sit.tim.tomatotrip.com/im/agent?appid=ADELUfkRseKRx9LFSq0CaWvJnqxsVdIdbkTMojyA5OtYFuzrG4Ic4FJvQTenWohTXDdvRnuBTcTLHsxoGZaCMnY8NNmlZKbirSzDjafgISZBToju7GMeCbg&userid=ADELUfk9_WdopoTSU7tJ1h0sXVUit5RyfkEzaPM1FDRBp_Fr8CcgblXkOwMif_ujcFzkY-70-rxz3-N66eiKBmdQ2UUxzyCf_g&ticket=ADELUfkeKnvMku5xmXlOHFzfXAFvuYl8M9RKJO3OQnmi4O4jwENf3j-Xt27UQK4B7cW7o9EHQhVOtsOZMlZf3xU5ag1oCVy1evbzq36d2KpWT1AK1jJ-Cf-hXrZreDeJ_SPvQVNAUxy7PcivAeVXdUcYysracfgn3HV243nOb8DNBn8e8oukFLlEoXph4UeXhEXSjEGtqV7gGscs_Ysp04pGM-a47iUf3zbP4ydS8DgMNA5ObQqq4UQ&sign=UGRvODlCeXZ0MjVHU0JnYXk0ZytjVXlNT3d3OEZBRk04Z0lja2ZNZHZJaVpPQUg4RGNFTklEckNTc0FUc2VOajR6dGdLVThQbzBQUHVNZW5nenRMOXc9PQ==&token=296eb4cb-3e6a-357b-a2ed-5f23dbd64868


> @stoneLee81 I am unable to connect to the URL mentioned from browser. Tried this. Can you confirm if your server is accepting connections?
> 
> ```js
> ws = new WebSocket("ws://192.168.122.96:15327/im/agent/socket.io/");
> ws.onmessage = function (e) { console.log(e.data); };
> ws.onopen = function() { ws.send("SomeMessage"); }
> ```

this is the address, can you try it?

https://sit.tim.tomatotrip.com/im/agent?appid=ADELUfkRseKRx9LFSq0CaWvJnqxsVdIdbkTMojyA5OtYFuzrG4Ic4FJvQTenWohTXDdvRnuBTcTLHsxoGZaCMnY8NNmlZKbirSzDjafgISZBToju7GMeCbg&userid=ADELUfk9_WdopoTSU7tJ1h0sXVUit5RyfkEzaPM1FDRBp_Fr8CcgblXkOwMif_ujcFzkY-70-rxz3-N66eiKBmdQ2UUxzyCf_g&ticket=ADELUfkeKnvMku5xmXlOHFzfXAFvuYl8M9RKJO3OQnmi4O4jwENf3j-Xt27UQK4B7cW7o9EHQhVOtsOZMlZf3xU5ag1oCVy1evbzq36d2KpWT1AK1jJ-Cf-hXrZreDeJ_SPvQVNAUxy7PcivAeVXdUcYysracfgn3HV243nOb8DNBn8e8oukFLlEoXph4UeXhEXSjEGtqV7gGscs_Ysp04pGM-a47iUf3zbP4ydS8DgMNA5ObQqq4UQ&sign=UGRvODlCeXZ0MjVHU0JnYXk0ZytjVXlNT3d3OEZBRk04Z0lja2ZNZHZJaVpPQUg4RGNFTklEckNTc0FUc2VOajR6dGdLVThQbzBQUHVNZW5nenRMOXc9PQ==&token=296eb4cb-3e6a-357b-a2ed-5f23dbd64868
