### ISSUE TITLE
How to find out the reason of "io.socket.engineio.client.EngineIOException: websocket error"

### ISSUE THREAD

**Issue by jerryzhoujw** [infitio/flutter_socket_io#134]
**Describe the bug**

I run the example folder, with replace of the WebSocket url with `wss://api.blablaapp.cn:443/models/stream/bosk?original=aaa`

But get error : `io.socket.engineio.client.EngineIOException: websocket error`

What should I do to find out the more detailed reason.

**Comment by lmr520** [comment]
are you resolve it?

**Comment by jerryzhoujw** [comment]
@Imr520 this error is gone, but not remember how solved.
