### ISSUE TITLE
Logging not displaying for iOS but Android is fine

### ISSUE THREAD

**Issue by smasinde** [infitio/flutter_socket_io#135]
**Describe the bug**
Logging is not showing for iOS but on Android they show.

**Have you tried reproducing the issue with example available in this repo?**
No

**Device details:**
 - Device Type: Simulator
 - Model: iPhone 11
 - OS: 13.5

**Relevant Logs**
The absence of logs is the issue

**Comment by Shashoug** [comment]
i'm facing the same issue now, any solutions?

**Comment by smasinde** [comment]
Unfortunately, no @Shashoug

**Comment by Shashoug** [comment]
i'm working on something now @smasinde , if anything pops i will ping you up.

**Comment by Shashoug** [comment]
@smasinde  
You have to run your iOS module with xcode to get your logs work,i have tried that. 
My issue is : nil host used in call to allowsSpecificHTTPSCertificateForHost.
Anyone able to fix that?

**Comment by Shashoug** [comment]
@smasinde  
You have to run your iOS module with xcode to get your logs work,i have tried that. 
My issue is : nil host used in call to allowsSpecificHTTPSCertificateForHost.
Anyone able to fix that?

**Comment by tiholic** [comment]
@smasinde as @Shashoug mentioned iOS logs will be displayed only when running the app from xcode.

**Comment by tiholic** [comment]
@Shashoug can you create a new issue with https related issue.
Also check if your server is accessible using a socket io js SDK on html page
