### ISSUE TITLE
How to emit map not list?

### ISSUE THREAD

**Issue by temirfe** [infitio/flutter_socket_io#15]
Is it possible to send data as Map directly for example `socket.emit("msg", {'key': 'value'});` instead of `socket.emit("msg", [{'key': 'value'}]);` ?
Sorry it's kinda a feature request.

**Comment by tiholic** [comment]
@temirfe It is not possible to send a map as per the design, but if your requirement is to receive data on server as simple arguments, that works already.

---

For example, 

client
```dart
socket.emit("msg", [
    {
        'text': 'hello',
        'to': '1234'
    }
]);
```

server
```js
socket.on("msg", function(msg){
    console.log("**NEW MESSAGE** ", msg);   //This will print { 'text': 'hello', 'to': '1234' }
});
```

----

If it is necessary for you to have a method which takes `map` as an argument, I recommend you to create a method which takes `event name` and `map` as argument and forwards that to `socket.emit` as `event name` and `array` of one item
