### ISSUE TITLE
Request to this repo contributors and maintainers

### ISSUE THREAD

**Issue by idevchandra** [infitio/flutter_socket_io#152]
I see that all the issues are assigned to @tiholic (Rohit Reddy Abbadi). Looks like he is not active on this repo anymore fixing the defects. None of the issues were responded. 

Can any of the repo contributors please take those defects from his plate?

Tagging: 
@Saifallak @alexHimik @HenrikThien @Vardiak @lhcdims @brooth @mirkancal @aslamanver @aurbina83

**Comment by Vardiak** [comment]
I personally switched to using socket_io_client which is a pure Dart implementation of the socket.io protocol. This approach should be prefered instead of using an old implementation of socket.io for Android and iOS with a Dart interface.

**Comment by idevchandra** [comment]
@Vardiak : Thanks much for quick response. Much appreciate it.

**Comment by idevchandra** [comment]
Closing issue!
