### ISSUE TITLE
Socket triggered::connect_error

### ISSUE THREAD

**Issue by AbdullahGaber** [infitio/flutter_socket_io#158]
when i try connecting to socket the connect_error triggered and throw the following exception:

D/Adhara:Socket( 8723): Socket triggered::connect_error
2
I/flutter ( 8723): connect error io.socket.engineio.client.EngineIOException: websocket error

I also added add android:useCleartextTraffic="true" inside the application tag of AndroidManifest.xml and internet permission .
and checked the port and domain ..

**Comment by tiholic** [comment]
@AbdullahGaber can you confirm if this issue was due to incompatible socket versions? Server should be using V2 sockets for this package to work smoothly.
