### ISSUE TITLE
Execution failed for task ':adhara_socket_io:generateDebugRFile'.

### ISSUE THREAD

**Issue by Hendaru** [infitio/flutter_socket_io#161]
I have error like this : 
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':adhara_socket_io:generateDebugRFile'.
> java.util.NoSuchElementException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
Exception: Gradle task assembleDebug failed with exit code 1

version adhara_socket_io: ^0.4.1

please help me :)

**Comment by tiholic** [comment]
@Hendaru please upgrade to latest version `1.0.0` and see of the issue still persists

**Comment by Hendaru** [comment]
> @Hendaru please upgrade to latest version `1.0.0` and see of the issue still persists

the problem if upgrade to latest version 1.0.0, flutter must upgrade as well, and if my flutter upgrade to latest version my application totally error. i use flutter 1.17.4
