### ISSUE TITLE
Listener when instance cleared

### ISSUE THREAD

**Issue by ariefwijaya** [infitio/flutter_socket_io#162]
Do we need to cancel listener manually after we call `  await socketIOManager.clearInstance(...);` ?

**Comment by tiholic** [comment]
@ariefwijaya It is always a good idea to manually close the listeners on an instance before clearing (possibly in your dispose method). However, the listeners should not be invoked once the instance is cleared.

> _Please share more details by updating the issue title/description if there is any unexpected behaviour_
