### ISSUE TITLE
Compilation errors on IOS with Socket.IO-Client-Swift (16.0.1)

### ISSUE THREAD

**Issue by dna-f** [infitio/flutter_socket_io#167]
Hi,
I recently got a few errors while compiling on iOS, after cleaning up pods

Podfile.lock reported the following version of Socket.IO-Client-Swift (16.0.1)

    - Socket.IO-Client-Swift (16.0.1):
      - Starscream (~> 4.0)

    - Starscream (4.0.4)

I downgraded it, reverting to my previous Podfile.lock version, and everything turned fine
    - Socket.IO-Client-Swift (15.2.0):
        - Starscream (~> 3.1)

    - Starscream (3.1.1)

**Comment by hetthakkar** [comment]
> Hi,
> I recently got a few errors while compiling on iOS, after cleaning up pods
> 
> Podfile.lock reported the following version of Socket.IO-Client-Swift (16.0.1)
> 
> ```
> - Socket.IO-Client-Swift (16.0.1):
>   - Starscream (~> 4.0)
> 
> - Starscream (4.0.4)
> ```
> 
> I downgraded it, reverting to my previous Podfile.lock version, and everything turned fine
> - Socket.IO-Client-Swift (15.2.0):
> - Starscream (~> 3.1)
> 
> ```
> - Starscream (3.1.1)
> ```

This fixed it for me as well. Thanks so much.. I should mention, I was trying to use version 0.4.2+1 of adhara_socket_io for my project. The code refused to compile for iOS

**Comment by bilalbaz1** [comment]
> Merhaba,
> son zamanlarda, podları temizledikten sonra iOS'ta derlerken birkaç hata aldım
> 
> Podfile.lock, Socket.IO-Client-Swift'in (16.0.1) aşağıdaki sürümünü bildirdi
> 
> ```
> - Socket.IO-Client-Swift (16.0.1):
>   - Starscream (~> 4.0)
> 
> - Starscream (4.0.4)
> ```
> 
> Onu düşürdüm, önceki Podfile.lock sürümüme döndüm ve her şey yolunda gitti
> - Socket.IO-Client-Swift (15.2.0):
> - Starscream (~> 3.1)
> 
> ```
> - Starscream (3.1.1)
> ```

**ios/Podfile.lock**
`PODS:
  - adhara_socket_io (0.0.1):
    - Flutter
    - Socket.IO-Client-Swift (15.2.0):
    - Starscream (3.1.1)
  - connectivity (0.0.1):
    - Flutter
    - Reachability
  - device_info (0.0.1):
    - Flutter
  - Firebase/CoreOnly (7.11.0):
    - FirebaseCore (= 7.11.0)
  - Firebase/Messaging (7.11.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 7.11.0)
  - firebase_core (1.1.1):
    - Firebase/CoreOnly (= 7.11.0)
    - Flutter
  - firebase_messaging (9.1.4):
    - Firebase/Messaging (= 7.11.0)
    - firebase_core
    - Flutter
  - FirebaseCore (7.11.0):
    - FirebaseCoreDiagnostics (~> 7.4)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/Logger (~> 7.0)
  - FirebaseCoreDiagnostics (7.11.0):
    - GoogleDataTransport (~> 8.4)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/Logger (~> 7.0)
    - nanopb (~> 2.30908.0)
  - FirebaseInstallations (7.11.0):
    - FirebaseCore (~> 7.0)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/UserDefaults (~> 7.0)
    - PromisesObjC (~> 1.2)
  - FirebaseInstanceID (7.11.0):
    - FirebaseCore (~> 7.0)
    - FirebaseInstallations (~> 7.0)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/UserDefaults (~> 7.0)
  - FirebaseMessaging (7.11.0):
    - FirebaseCore (~> 7.0)
    - FirebaseInstallations (~> 7.0)
    - FirebaseInstanceID (~> 7.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.0)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/Reachability (~> 7.0)
    - GoogleUtilities/UserDefaults (~> 7.0)
  - Flutter (1.0.0)
  - flutter_inappwebview (0.0.1):
    - Flutter
    - flutter_inappwebview/Core (= 0.0.1)
    - OrderedSet (~> 5.0)
  - flutter_inappwebview/Core (0.0.1):
    - Flutter
    - OrderedSet (~> 5.0)
  - flutter_keyboard_visibility (0.0.1):
    - Flutter
  - flutter_local_notifications (0.0.1):
    - Flutter
  - fluttertoast (0.0.2):
    - Flutter
    - Toast
  - FMDB (2.7.5):
    - FMDB/standard (= 2.7.5)
  - FMDB/standard (2.7.5)
  - GoogleDataTransport (8.4.0):
    - GoogleUtilities/Environment (~> 7.2)
    - nanopb (~> 2.30908.0)
    - PromisesObjC (~> 1.2)
  - GoogleUtilities/AppDelegateSwizzler (7.4.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (7.4.0):
    - PromisesObjC (~> 1.2)
  - GoogleUtilities/Logger (7.4.0):
    - GoogleUtilities/Environment
  - GoogleUtilities/Network (7.4.0):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (7.4.0)"
  - GoogleUtilities/Reachability (7.4.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (7.4.0):
    - GoogleUtilities/Logger
  - image_cropper (0.0.4):
    - Flutter
    - TOCropViewController (~> 2.6.0)
  - image_picker (0.0.1):
    - Flutter
  - in_app_purchase (0.0.1):
    - Flutter
  - in_app_review (0.2.0):
    - Flutter
  - nanopb (2.30908.0):
    - nanopb/decode (= 2.30908.0)
    - nanopb/encode (= 2.30908.0)
  - nanopb/decode (2.30908.0)
  - nanopb/encode (2.30908.0)
  - OrderedSet (5.0.0)
  - path_provider (0.0.1):
    - Flutter
  - PromisesObjC (1.2.12)
  - Reachability (3.2)
  - shared_preferences (0.0.1):
    - Flutter
  - Socket.IO-Client-Swift (13.3.1):
    - Starscream (~> 3.0.2)
  - sqflite (0.0.2):
    - Flutter
    - FMDB (>= 2.7.5)
  - Starscream (3.0.6)
  - Toast (4.0.0)
  - TOCropViewController (2.6.0)
  - unique_identifier (0.0.1):
    - Flutter
  - url_launcher (0.0.1):
    - Flutter

DEPENDENCIES:
  - adhara_socket_io (from `.symlinks/plugins/adhara_socket_io/ios`)
  - connectivity (from `.symlinks/plugins/connectivity/ios`)
  - device_info (from `.symlinks/plugins/device_info/ios`)
  - firebase_core (from `.symlinks/plugins/firebase_core/ios`)
  - firebase_messaging (from `.symlinks/plugins/firebase_messaging/ios`)
  - Flutter (from `Flutter`)
  - flutter_inappwebview (from `.symlinks/plugins/flutter_inappwebview/ios`)
  - flutter_keyboard_visibility (from `.symlinks/plugins/flutter_keyboard_visibility/ios`)
  - flutter_local_notifications (from `.symlinks/plugins/flutter_local_notifications/ios`)
  - fluttertoast (from `.symlinks/plugins/fluttertoast/ios`)
  - image_cropper (from `.symlinks/plugins/image_cropper/ios`)
  - image_picker (from `.symlinks/plugins/image_picker/ios`)
  - in_app_purchase (from `.symlinks/plugins/in_app_purchase/ios`)
  - in_app_review (from `.symlinks/plugins/in_app_review/ios`)
  - path_provider (from `.symlinks/plugins/path_provider/ios`)
  - shared_preferences (from `.symlinks/plugins/shared_preferences/ios`)
  - Socket.IO-Client-Swift (~> 13.3.0)
  - sqflite (from `.symlinks/plugins/sqflite/ios`)
  - unique_identifier (from `.symlinks/plugins/unique_identifier/ios`)
  - url_launcher (from `.symlinks/plugins/url_launcher/ios`)

SPEC REPOS:
  trunk:
    - Firebase
    - FirebaseCore
    - FirebaseCoreDiagnostics
    - FirebaseInstallations
    - FirebaseInstanceID
    - FirebaseMessaging
    - FMDB
    - GoogleDataTransport
    - GoogleUtilities
    - nanopb
    - OrderedSet
    - PromisesObjC
    - Reachability
    - Socket.IO-Client-Swift
    - Starscream
    - Toast
    - TOCropViewController

EXTERNAL SOURCES:
  adhara_socket_io:
    :path: ".symlinks/plugins/adhara_socket_io/ios"
  connectivity:
    :path: ".symlinks/plugins/connectivity/ios"
  device_info:
    :path: ".symlinks/plugins/device_info/ios"
  firebase_core:
    :path: ".symlinks/plugins/firebase_core/ios"
  firebase_messaging:
    :path: ".symlinks/plugins/firebase_messaging/ios"
  Flutter:
    :path: Flutter
  flutter_inappwebview:
    :path: ".symlinks/plugins/flutter_inappwebview/ios"
  flutter_keyboard_visibility:
    :path: ".symlinks/plugins/flutter_keyboard_visibility/ios"
  flutter_local_notifications:
    :path: ".symlinks/plugins/flutter_local_notifications/ios"
  fluttertoast:
    :path: ".symlinks/plugins/fluttertoast/ios"
  image_cropper:
    :path: ".symlinks/plugins/image_cropper/ios"
  image_picker:
    :path: ".symlinks/plugins/image_picker/ios"
  in_app_purchase:
    :path: ".symlinks/plugins/in_app_purchase/ios"
  in_app_review:
    :path: ".symlinks/plugins/in_app_review/ios"
  path_provider:
    :path: ".symlinks/plugins/path_provider/ios"
  shared_preferences:
    :path: ".symlinks/plugins/shared_preferences/ios"
  sqflite:
    :path: ".symlinks/plugins/sqflite/ios"
  unique_identifier:
    :path: ".symlinks/plugins/unique_identifier/ios"
  url_launcher:
    :path: ".symlinks/plugins/url_launcher/ios"

SPEC CHECKSUMS:
  adhara_socket_io: 7de66d78a4631172aca030e50839b29da6b42171
  connectivity: c4130b2985d4ef6fd26f9702e886bd5260681467
  device_info: d7d233b645a32c40dfdc212de5cf646ca482f175
  Firebase: c121feb35e4126c0b355e3313fa9b487d47319fd
  firebase_core: 54856a8a39b8f3e35f34fdd3373f3b92a1daa68b
  firebase_messaging: 64d2a9b095bc7afa54eff3f4e13522d9098619d2
  FirebaseCore: 907447d8917a4d3eb0cce2829c5a0ad21d90b432
  FirebaseCoreDiagnostics: 68ad972f99206cef818230f3f3179d52ccfb7f8c
  FirebaseInstallations: a58d4f72ec5861840b84df489f2668d970df558a
  FirebaseInstanceID: ad5135045a498d7775903efd39762d2cdfa1be27
  FirebaseMessaging: 163435fb6db065e3b6228f1e577b10ed2cc506d2
  Flutter: 434fef37c0980e73bb6479ef766c45957d4b510c
  flutter_inappwebview: bfd58618f49dc62f2676de690fc6dcda1d6c3721
  flutter_keyboard_visibility: 0339d06371254c3eb25eeb90ba8d17dca8f9c069
  flutter_local_notifications: 0c0b1ae97e741e1521e4c1629a459d04b9aec743
  fluttertoast: 6122fa75143e992b1d3470f61000f591a798cc58
  FMDB: 2ce00b547f966261cd18927a3ddb07cb6f3db82a
  GoogleDataTransport: cd9db2180fcecd8da1b561aea31e3e56cf834aa7
  GoogleUtilities: 284cddc7fffc14ae1907efb6f78ab95c1fccaedc
  image_cropper: f1668dd8d2cad2d357955caad15a40547856edcb
  image_picker: 50e7c7ff960e5f58faa4d1f4af84a771c671bc4a
  in_app_purchase: 3e2155afa9d03d4fa32d9e62d567885080ce97d6
  in_app_review: 4a97249f7a2f539a0f294c2d9196b7fe35e49541
  nanopb: a0ba3315591a9ae0a16a309ee504766e90db0c96
  OrderedSet: aaeb196f7fef5a9edf55d89760da9176ad40b93c
  path_provider: abfe2b5c733d04e238b0d8691db0cfd63a27a93c
  PromisesObjC: 3113f7f76903778cf4a0586bd1ab89329a0b7b97
  Reachability: 33e18b67625424e47b6cde6d202dce689ad7af96
  shared_preferences: af6bfa751691cdc24be3045c43ec037377ada40d
  Socket.IO-Client-Swift: 79f8f85fa44881838175a20f9bd2c32bef2c9d37
  sqflite: 6d358c025f5b867b29ed92fc697fd34924e11904
  Starscream: ef3ece99d765eeccb67de105bfa143f929026cf5
  Toast: 91b396c56ee72a5790816f40d3a94dd357abc196
  TOCropViewController: 3105367e808b7d3d886a74ff59bf4804e7d3ab38
  unique_identifier: ebb92b4bc4ad9c2c93f85cb5e02f70ad168a2bd6
  url_launcher: 6fef411d543ceb26efce54b05a0a40bfd74cbbef

PODFILE CHECKSUM: 6f4c0b3ffeaff22bf5d0bd8f91ccb351302434eb

COCOAPODS: 1.10.1
`


**Debug Console**

`    end
    ```
    ### Error
    ```
    NoMethodError - undefined method `each' for nil:NilClass
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer/locking_dependency_analyzer.rb:96:in `block in add_to_dependency_graph'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer/locking_dependency_analyzer.rb:94:in `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer/locking_dependency_analyzer.rb:94:in `add_to_dependency_graph'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer/locking_dependency_analyzer.rb:96:in `block (2 levels) in add_to_dependency_graph'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer/locking_dependency_analyzer.rb:96:in `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer/locking_dependency_analyzer.rb:96:in `block in add_to_dependency_graph'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer/locking_dependency_analyzer.rb:94:in `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer/locking_dependency_analyzer.rb:94:in `add_to_dependency_graph'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer/locking_dependency_analyzer.rb:45:in `block in generate_version_locking_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer/locking_dependency_analyzer.rb:44:in `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer/locking_dependency_analyzer.rb:44:in `generate_version_locking_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:937:in `generate_version_locking_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:123:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:414:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:160:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'
    ```
    ――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
    [!] Oh no, an error occurred.
    Search for existing GitHub issues similar to yours:
    https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60each%27+for+nil%3ANilClass&type=Issues
    If none exists, create a ticket, with the template displayed above, on:
    https://github.com/CocoaPods/CocoaPods/issues/new
    Be sure to first read the contributing guide for details on how to properly submit a ticket:
    https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md
    Don't forget to anonymize any private data!
    Looking for related issues on cocoapods/cocoapods...
     - undefined method `map' for nil:NilClass
       https://github.com/CocoaPods/CocoaPods/issues/10613 [closed] [1 comment]
       a week ago
     - NoMethodError - undefined method `real_path`
       https://github.com/CocoaPods/CocoaPods/issues/8082 [open] [13 comments]
       25 Feb 2019
     - CocoaPods 1.9.3 update 1.10.1 error
       https://github.com/CocoaPods/CocoaPods/issues/10595 [open] [0 comments]
       3 weeks ago
    and 198 more at:
    https://github.com/cocoapods/cocoapods/search?q=undefined%20method%20%60each%27%20for%20nil&type=Issues&utf8=✓
Error output from CocoaPods:
↳
    [!] Automatically assigning platform `iOS` with version `12.1` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
 `

**What could be the cause of the problem?**

**Comment by bilalbaz1** [comment]
flutter_project/ios/Podfile.lock
`
...
- Socket.IO-Client-Swift (15.2.0):
    - Starscream (~> 3.1)
- Starscream (3.1.1)
...
`
I changed it that way and it worked. Thanks @dna-f
