### ISSUE TITLE
Socket not working on iOS because of namespace issue.

### ISSUE THREAD

**Issue by amsmu** [infitio/flutter_socket_io#17]
Socket not working on iOS because of namespace issue.

https://github.com/infitio/flutter_socket_io/blob/master/ios/Classes/AdharaSocket.swift 

Above file doesn't have any code for namespace.
It should be like this. 

let manager = SocketManager(socketURL: URL(string:"http://localhost:8080/")!)
let defaultNamespaceSocket = manager.defaultSocket
let swiftSocket = manager.socket(forNamespace: "/swift")

**Comment by tiholic** [comment]
@amsmu name spaces are not supported currently. Please add support for this from iOS side and create a PR if you can.

**Comment by tiholic** [comment]
Support for iOS added in https://github.com/infitio/flutter_socket_io/pull/52
Upgrade to 0.3.0 or higher
