### ISSUE TITLE
socket.off(eventName) is removed in 1.0.1+1

### ISSUE THREAD

**Issue by RageshAntony** [infitio/flutter_socket_io#176]
**Metadata**
 - Plugin version used: `ex: 1.0.1+1`
 - Server socket.io version: `ex: 2.4.0`
 - Device Type: [Physical Device or Emulator]
 - Model: [e.g. iPhone6]
 - OS: [e.g. iOS14.2 / Android API Level 29]
 - Package Version [e.g. 22]

Have you tried reproducing the issue with example available in this repo?: Yes/No

**Describe the bug**
socket.off(eventName) is removed in 1.0.1+1 . Please tell me the replacing function

**Steps to reproduce**
Add steps to reproduce the behavior

**Expected behavior**

**Relevant Logs**
```
Add any relevant logs about the problem here.
```

**Comment by starction** [comment]
New version uses steams to listen and cancel subscriptions. Please see the change log here: https://github.com/infitio/flutter_socket_io/blob/main/CHANGELOG.md#100---3rd-apr-2020

**Comment by RageshAntony** [comment]
Ok

Please update pub dev documentation with all new changes
