### ISSUE TITLE
XHR poll error (transports error) on AWS Elastic beanstalk

### ISSUE THREAD

**Issue by mgolob94** [infitio/flutter_socket_io#21]
Console returns me this errors:

I/flutter (10845): On error: io.socket.engineio.client.EngineIOException: xhr poll error
I/flutter (10845): Disconected: transport error

Is this problem on Flutter app or in server configuration? 
I hosting sockets on AWS.

Thanks for help.

**Comment by tiholic** [comment]
@mgolob94 are you using elastic beanstalk?

**Comment by mgolob94** [comment]
> @mgolob94 are you using elastic beanstalk?

Yes..

**Comment by tiholic** [comment]
@mgolob94 

You need to add a new file: `.ebextensions/socketupgrade.cofnig` with this content

```
container_commands:
  enable_websockets:
    command: |
     sed -i '/\s*proxy_set_header\s*Connection/c \
              proxy_set_header Upgrade $http_upgrade;\
              proxy_set_header Connection "upgrade";\
      ' /tmp/deployment/config/#etc#nginx#conf.d#00_elastic_beanstalk_proxy.conf
```
