### ISSUE TITLE
[Question] SSL

### ISSUE THREAD

**Issue by marianoarga** [infitio/flutter_socket_io#22]
Does this plugin work with socket.io server using HTTPS?

**Comment by tiholic** [comment]
@marianoarga it will.

**Comment by marianoarga** [comment]
Got HTTPS working today, thank you.

**Comment by KyawNaingTun** [comment]
Hi @marianoarga, how did you fixed? Please share me.

**Comment by tiholic** [comment]
@marianoarga share your fix here, it could help others

**Comment by marianoarga** [comment]
@KyawNaingTun @tiholic I don't quite remember my problem, I think I forgot to add "secure" parameter when running my socket.io server
https://socket.io/docs/server-api/#socket-handshake

**Comment by KyawNaingTun** [comment]
I have solved my problem. My issue wasn't related this package. So, I added the following lines in nginx host config file. That's all. Thanks @marianoarga 

`proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection 'upgrade';
  proxy_set_header Host $host;
  proxy_cache_bypass $http_upgrade;
  proxy_pass      http://localhost:$http_port;`
