### ISSUE TITLE
Getting error while running on IOS

### ISSUE THREAD

**Issue by rajeshzmoke** [infitio/flutter_socket_io#23]
Running Xcode build...                                                  
                                                   
Xcode build done.                                           13.6s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    /Users/rajeshkumar/Desktop/loop/ios/Pods/FMDB/src/fmdb/FMDatabase.m:1486:15: warning: 'sqlite3_wal_checkpoint_v2' is only available on iOS 5.0 or newer [-Wunguarded-availability]
        int err = sqlite3_wal_checkpoint_v2(_db, dbName, checkpointMode, logFrameCount, checkpointCount);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'SQLite3' imported from /Users/rajeshkumar/Desktop/loop/ios/Pods/FMDB/src/fmdb/FMDatabase.m:8:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/usr/include/sqlite3.h:8245:16: note: 'sqlite3_wal_checkpoint_v2' has been marked as
    being introduced in iOS 5.0 here, but the deployment target is iOS 4.3.0
    SQLITE_API int sqlite3_wal_checkpoint_v2(
                   ^
    /Users/rajeshkumar/Desktop/loop/ios/Pods/FMDB/src/fmdb/FMDatabase.m:1486:15: note: enclose 'sqlite3_wal_checkpoint_v2' in an @available check to silence this warning
        int err = sqlite3_wal_checkpoint_v2(_db, dbName, checkpointMode, logFrameCount, checkpointCount);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~
    1 warning generated.
    /Users/rajeshkumar/Desktop/loop/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.m:101:9: warning: 'dispatch_queue_set_specific' is only available on iOS 5.0 or newer [-Wunguarded-availability]
            dispatch_queue_set_specific(_queue, kDispatchQueueSpecificKey, (__bridge void *)self, NULL);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'Foundation' imported from /Users/rajeshkumar/Desktop/loop/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.h:9:
    In module 'CoreFoundation' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
    In module 'Dispatch' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/usr/include/dispatch/queue.h:1352:1: note: 'dispatch_queue_set_specific' has been
    marked as being introduced in iOS 5.0 here, but the deployment target is iOS 4.3.0
    dispatch_queue_set_specific(dispatch_queue_t queue, const void *key,
    ^
    /Users/rajeshkumar/Desktop/loop/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.m:101:9: note: enclose 'dispatch_queue_set_specific' in an @available check to silence this warning
            dispatch_queue_set_specific(_queue, kDispatchQueueSpecificKey, (__bridge void *)self, NULL);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/rajeshkumar/Desktop/loop/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.m:184:54: warning: 'dispatch_get_specific' is only available on iOS 5.0 or newer [-Wunguarded-availability]
        FMDatabaseQueue *currentSyncQueue = (__bridge id)dispatch_get_specific(kDispatchQueueSpecificKey);
                                                         ^~~~~~~~~~~~~~~~~~~~~
    In module 'Foundation' imported from /Users/rajeshkumar/Desktop/loop/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.h:9:
    In module 'CoreFoundation' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
    In module 'Dispatch' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/usr/include/dispatch/queue.h:1408:1: note: 'dispatch_get_specific' has been marked as
    being introduced in iOS 5.0 here, but the deployment target is iOS 4.3.0
    dispatch_get_specific(const void *key);
    ^
    /Users/rajeshkumar/Desktop/loop/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.m:184:54: note: enclose 'dispatch_get_specific' in an @available check to silence this warning
        FMDatabaseQueue *currentSyncQueue = (__bridge id)dispatch_get_specific(kDispatchQueueSpecificKey);
                                                         ^~~~~~~~~~~~~~~~~~~~~
    2 warnings generated.
    /Users/rajeshkumar/.pub-cache/hosted/pub.dartlang.org/local_auth-0.4.0+1/ios/Classes/LocalAuthPlugin.m:115:33: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate
    this is intended behavior [-Wimplicit-retain-self]
                                    lastCallArgs = arguments;
                                    ^
                                    self->
    /Users/rajeshkumar/.pub-cache/hosted/pub.dartlang.org/local_auth-0.4.0+1/ios/Classes/LocalAuthPlugin.m:116:33: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate
    this is intended behavior [-Wimplicit-retain-self]
                                    lastResult = result;
                                    ^
                                    self->
    2 warnings generated.
    === BUILD TARGET Socket.IO-Client-Swift OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/rajeshkumar/Desktop/loop/ios/Pods/Socket.IO-Client-Swift/Source/SocketIO/Ack/SocketAckManager.swift:39:9: warning: 'Hashable.hashValue' is deprecated as a protocol requirement;
    conform type 'SocketAck' to 'Hashable' by implementing 'hash(into:)' instead
        var hashValue: Int {
            ^
    /Users/rajeshkumar/Desktop/loop/ios/Pods/Socket.IO-Client-Swift/Source/SocketIO/Client/SocketIOClientSpec.swift:239:5: warning: 'public' modifier is redundant for instance method declared in
    a public extension
        public func didError(reason: String) {
        ^~~~~~~

    /Users/rajeshkumar/Desktop/loop/ios/Pods/Socket.IO-Client-Swift/Source/SocketIO/Parse/SocketPacket.swift:161:5: warning: 'public' modifier is redundant for enum declared in a public
    extension
        public enum PacketType: Int {
        ^~~~~~~

    /Users/rajeshkumar/Desktop/loop/ios/Pods/Socket.IO-Client-Swift/Source/SocketIO/Parse/SocketParsable.swift:146:5: warning: 'public' modifier is redundant for instance method declared in a
    public extension
        public func parseSocketMessage(_ message: String) -> SocketPacket? {
        ^~~~~~~

    /Users/rajeshkumar/Desktop/loop/ios/Pods/Socket.IO-Client-Swift/Source/SocketIO/Parse/SocketParsable.swift:172:5: warning: 'public' modifier is redundant for instance method declared in a
    public extension
        public func parseBinaryData(_ data: Data) -> SocketPacket? {
        ^~~~~~~

    /Users/rajeshkumar/Desktop/loop/ios/Pods/Socket.IO-Client-Swift/Source/SocketIO/Ack/SocketAckManager.swift:39:9: warning: 'Hashable.hashValue' is deprecated as a protocol requirement;
    conform type 'SocketAck' to 'Hashable' by implementing 'hash(into:)' instead
        var hashValue: Int {
            ^
    /Users/rajeshkumar/Desktop/loop/ios/Pods/Socket.IO-Client-Swift/Source/SocketIO/Parse/SocketPacket.swift:161:5: warning: 'public' modifier is redundant for enum declared in a public
    extension
        public enum PacketType: Int {
        ^~~~~~~

    /Users/rajeshkumar/Desktop/loop/ios/Pods/Socket.IO-Client-Swift/Source/SocketIO/Parse/SocketParsable.swift:146:5: warning: 'public' modifier is redundant for instance method declared in a
    public extension
        public func parseSocketMessage(_ message: String) -> SocketPacket? {
        ^~~~~~~

    /Users/rajeshkumar/Desktop/loop/ios/Pods/Socket.IO-Client-Swift/Source/SocketIO/Parse/SocketParsable.swift:172:5: warning: 'public' modifier is redundant for instance method declared in a
    public extension
        public func parseBinaryData(_ data: Data) -> SocketPacket? {
        ^~~~~~~

    /Users/rajeshkumar/Desktop/loop/ios/Pods/Socket.IO-Client-Swift/Source/SocketIO/Ack/SocketAckManager.swift:39:9: warning: 'Hashable.hashValue' is deprecated as a protocol requirement;
    conform type 'SocketAck' to 'Hashable' by implementing 'hash(into:)' instead
        var hashValue: Int {
            ^
    === BUILD TARGET adhara_socket_io OF PROJECT Pods WITH CONFIGURATION Debug ===
    <module-includes>:1:9: note: in file included from <module-includes>:1:
    #import "adhara_socket_io-umbrella.h"
            ^
    /Users/rajeshkumar/Desktop/loop/ios/Pods/Headers/Public/adhara_socket_io/adhara_socket_io-umbrella.h:13:9: note: in file included from
    /Users/rajeshkumar/Desktop/loop/ios/Pods/Headers/Public/adhara_socket_io/adhara_socket_io-umbrella.h:13:
    #import "AdharaSocketIoPlugin.h"
            ^
    /Users/rajeshkumar/Desktop/loop/ios/Pods/Headers/Public/adhara_socket_io/AdharaSocketIoPlugin.h:1:9: error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^
    <unknown>:0: error: could not build Objective-C module 'adhara_socket_io'
    === BUILD TARGET adhara_socket_io OF PROJECT Pods WITH CONFIGURATION Debug ===
    <module-includes>:1:9: note: in file included from <module-includes>:1:
    #import "adhara_socket_io-umbrella.h"
            ^
    /Users/rajeshkumar/Desktop/loop/ios/Pods/Headers/Public/adhara_socket_io/adhara_socket_io-umbrella.h:13:9: note: in file included from
    /Users/rajeshkumar/Desktop/loop/ios/Pods/Headers/Public/adhara_socket_io/adhara_socket_io-umbrella.h:13:
    #import "AdharaSocketIoPlugin.h"
            ^
    /Users/rajeshkumar/Desktop/loop/ios/Pods/Headers/Public/adhara_socket_io/AdharaSocketIoPlugin.h:1:9: error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^
    <unknown>:0: error: could not build Objective-C module 'adhara_socket_io'

Could not build the precompiled application for the device.

Error launching application on HighPeaksw iPhone X.

**Comment by tiholic** [comment]
@rajeshzmoke can you try pointing your pubspec dependency to the repo.

**Comment by rajeshzmoke** [comment]
@tiholic yea that fixed the issue can build iOS now,

**Comment by rajeshzmoke** [comment]
@tiholic but the ios doesnt hit the node js socket server, android works great ..any idea as to why?

**Comment by tiholic** [comment]
@rajeshzmoke great. Will release an update on Pub.
Can you share iOS logs?

**Comment by tiholic** [comment]
@rajeshzmoke  ios issue fixed and released in [0.1.11](https://pub.dev/packages/adhara_socket_io/versions/0.1.11)

**Comment by rajeshzmoke** [comment]
@tiholoc how do i share logs?

**Comment by tiholic** [comment]
@rajeshzmoke what do you mean by sharing logs?

If you want to see more logs enable logging pass `enableLogging: true,` in SocketOptions
