### ISSUE TITLE
io.socket.engineio.client.EngineIOException: xhr poll error

### ISSUE THREAD

**Issue by theromie** [infitio/flutter_socket_io#28]
> manager = SocketIOManager();
>     setState(() => isProbablyConnected = true);
>     socket =
>         await manager.createInstance(socketUrl, query: {}, enableLogging: true);
>     socket.onConnect((data) {
>       print("connected...$data");
>       socket.emit("message", ["Hello World"]);
>     });
>     socket.onConnectError(pprint);
>     socket.onConnectTimeout(pprint);
>     socket.onError(pprint);
>     socket.onDisconnect(pprint);
>     socket.on('news', (data) {
>       print("hi" + data);
>     });
>     socket.connect();

I am running flutter app on real device and trying to connect socket on my server IP but it failed to connect.

**Comment by tiholic** [comment]
@theromie Where is your server hosted? In your intranet or on AWS?

**Comment by theromie** [comment]
As of now testing on local machine

**Comment by theromie** [comment]
and even my test server is on AWS @tiholic

**Comment by theromie** [comment]
`D/Adhara:Socket( 1414): Socket triggered::connect_error
I/flutter ( 1414): io.socket.engineio.client.EngineIOException: xhr poll error`

**Comment by theromie** [comment]
> const io = require ('socket.io') (server, {
>   transports: ['polling'],
> });
> app.use ((request, response, next) => {
>   response.io = io;
>   next ();
> });
> io.on ('connection', client => {
>   client.on ('message', function (data) {
>     console.log (data.my);
>     io.emit ('news', data.my);
>   });
>   client.on ('disconnect', () => {
>     console.log ('disconnect');
>   });
>   client.on ('error', error => {
>     console.log (error);
>   });
> });

**Comment by theromie** [comment]
Working on emulator but disconnects and Connects again every time

**Comment by theromie** [comment]
> D/Adhara:Socket( 4042): Socket triggered::connect
> I/flutter ( 4042): Connected
> D/Adhara:Socket( 4042): Socket triggered::error
> I/flutter ( 4042): io.socket.engineio.client.EngineIOException: xhr poll error
> D/Adhara:Socket( 4042): Socket triggered::disconnect
> I/flutter ( 4042): transport error
> D/Adhara:Socket( 4042): Socket triggered::connect
> I/flutter ( 4042): Connected

**Comment by theromie** [comment]
Not working with Android Pie 9 @tiholic

**Comment by tiholic** [comment]
> D/Adhara:Socket(26387): Connecting to... http://IP Address:3000/

Please point your [IP Address](https://github.com/infitio/flutter_socket_io/blob/master/example/lib/main.dart#L7) properly.

Seems like your mobile is not getting connected to server IP

**Comment by theromie** [comment]
It's working with lower Android version but not with Pie 9. Please update your package based on Pie

**Comment by lhcdims** [comment]
> It's working with lower Android version but not with Pie 9. Please update your package based on Pie

pie by default only support https, you need to add:

android:useCleartextTraffic="true"

inside the <application> tag of AndroidManifest.xml 

in order to use http in Android Pie

**Comment by Amriksinghkis** [comment]
Not working give same error "io.socket.engineio.client.EngineIOException: xhr poll error"

**Comment by theromie** [comment]
pie by default only support https, you need to add:

android:useCleartextTraffic="true"

inside the application tag of AndroidManifest.xml

in order to use http in Android Pie

@amirksinghkis

**Comment by Amriksinghkis** [comment]
@theromie  not working for me, if add android:useCleartextTraffic="true"
inside the application tag of AndroidManifest.xml then it give below error:
error: attribute android:useCleartextTraffic not found.

**Comment by lhcdims** [comment]
'inside application tag' means:

```
<application
  android:usesCleartextTraffic="true"
>
  ...something else
</application>
```

**Comment by theromie** [comment]
Yes @lhcdims

**Comment by Amriksinghkis** [comment]
It is working now, My bad no clean the code after above changes, then I have clean the code it working fine. Thanks theromie for help..

**Comment by tiholic** [comment]
Added necessary details in README

**Comment by castrojr913** [comment]
> Not working give same error "io.socket.engineio.client.EngineIOException: xhr poll error" for Android Pie
@tiholic I added the android:usesCleartextTraffic="true" on <application> tag and It didn't work

**Comment by LuongHai-7buon** [comment]
@castrojr913 Have you solved this problem?

**Comment by vksBhardwaj** [comment]
Any body solved  this issue am getting same error

**Comment by ashifa454** [comment]
did anyone found a solution for this issue?

**Comment by vksBhardwaj** [comment]
got it solution for this error

**Comment by theromie** [comment]
pie by default only support https, you need to add:

android:useCleartextTraffic="true"

inside the application tag of AndroidManifest.xml

in order to use http in Android Pie
