### ISSUE TITLE
Socket not connecting on iOS emulator

### ISSUE THREAD

**Issue by solnsumei** [infitio/flutter_socket_io#29]
When I try running the app using the example code from the adhara socket plugin on iOS, nothing happens. It neither connects, emits a message or even throw an error. 
Runs as expected on Android and the mobile browser.

**Expected behavior**
Should display, connected and message received from the socket server.

**Device details:**
 - Device: [e.g. iPhoneXr Emulator]
 - OS: [e.g. iOS12]

**Comment by Amriksinghkis** [comment]
I am facing same issue, Any update of same?

**Comment by indranil-tiwary** [comment]
Same issue. Any updates?

**Comment by DanielR97** [comment]
For me, it works on Android but tries to connect infinitely on iOS.

Try `enableLogging: true` on the socket options and either use an older simulator (e.g. iPhone 7 with iOS 10) or run with Xcode for more log messages.

**Comment by tiholic** [comment]
@DanielR97 namespace support for iOS is added now. Upgrade to 0.3.2

**Comment by diegoalvis** [comment]
Still having the issue with version 0.3.2

**Comment by solnsumei** [comment]
let me try it out

**Comment by tiholic** [comment]
@solnsumei Is it resolved now?
Try with 0.3.4

@Amriksinghkis @indranil-tiwary @diegoalvis @solnsumei 
See if this can help: https://github.com/infitio/infitio.github.io/blob/master/adhara_socketio.mov

**Comment by rhessus** [comment]
I have the same issue with the 0.3.4. Socket with namespace not connecting

**Comment by yalshamy** [comment]
I have the same issue with the 0.3.5.

Device details:
Device: [e.g. iPhoneXr Emulator]
OS: [e.g. iOS12]

**Comment by yalshamy** [comment]
After debugging I found the problem happened because the socket request uses polling transport, not WebSocket transport although I removed `Transports.POLLING` from transports options and kept on 'Transports.WEB_SOCKET'.

This problem only occurred in ios and android working fine.

**Comment by Mohammad-ezzidden** [comment]
I have the same issue as well the socket not connect and trigger disconnect many times , 
Im also just using websocket transport., Any solution ?

**Comment by vincentsong** [comment]
for iOS namespace problem, please use SocketOptions correctly:

`SocketOptions(_domain, nameSpace: '/yourNS');`

**Comment by tiholic** [comment]
@vincentsong Yes, it must work the same on both platforms. In the example, it works good for both Android and iOS (https://github.com/infitio/flutter_socket_io/blob/master/example/lib/main.dart#L32)

Are you not able to connect on both platforms with same options?

**Comment by vincentsong** [comment]
I can connect on both of the platform. Just need to add namespace in SocketOptions for iOS

**Comment by tiholic** [comment]
@vincentsong setting `url` as `http://localhost:3000` and `namespace` as '/mynamespace' doesn't work on both the platforms?

**Comment by vincentsong** [comment]
> @vincentsong setting `url` as `http://localhost:3000` and `namespace` as `/mynamespace` doesn't work on both the platforms?

@tiholic  only work for iOS, I have to put url like this 'http://localhost:3000/mynamespace' to make it working on android.

**Comment by tiholic** [comment]
@vincentsong thanks for pointing it out!
It would be great if you can make necessary changes for android and raise a PR.

**Comment by vincentsong** [comment]
> @vincentsong thanks for pointing it out!
> It would be great if you can make necessary changes for android and raise a PR.

Sure, I think I need to create a new issue instead of using this ticket here. :)

**Comment by tiholic** [comment]
@solnsumei @Amriksinghkis @indranil-tiwary @DanielR97 @diegoalvis @rhessus @yalshamy @vincentsong 

V1.0.0 ensures support for namespaces on both platforms with necessary integration tests. Please test and create a new issue if there are any.
