### ISSUE TITLE
error: could not build Objective-C module 'Starscream'

### ISSUE THREAD

**Issue by VesperHan** [infitio/flutter_socket_io#31]
**Describe the bug**
    <unknown>:0: error: could not build Objective-C module 'Starscream'
      umbrella header "Starscream-umbrella.h"

**To Reproduce**
My proj is objc language, i have integrate it and change config to support swift . when  i build show this error.

**Comment by VesperHan** [comment]
xcode 10.2.1 cannot support swift3.x

**Comment by tiholic** [comment]
@VesperHan try with 0.3.1 and let know

**Comment by tiholic** [comment]
https://github.com/infitio/flutter_socket_io/pull/18
