### ISSUE TITLE
 Error when I put the second parameter as callback

### ISSUE THREAD

**Issue by Aguezz** [infitio/flutter_socket_io#37]
// Client
socket.emit('my event name', ['my first param', (message) {
   print(message);
} ] );

// Server [Node]
socket.on('my event name', (data, callback) => {
   return callback('Success');
} ] )

When I run the function, I got an error "Invalid argument: Closure: (dynamic) => Null"

**Comment by Reneuve** [comment]
Yes, i got the same problem with him too

**Comment by tiholic** [comment]
@Aguezz currently supported format is `socket.emit("message", ["Hello world!"]);`

What exactly are you trying to achieve by passing a function?

**Comment by tiholic** [comment]
@Aguezz @Reneuve ACK Support is now implemented. Upgrade to 0.3.0 or higher
