### ISSUE TITLE
Error when received event data is a string and not List

### ISSUE THREAD

**Issue by daniwaxman** [infitio/flutter_socket_io#38]
**Describe the bug**
If the event data received from the server is not formatted as JSON an exception is thrown. 

**To Reproduce**
1. Modify the server send message to be:
socket.emit('news',  'hello world');

**Expected behavior**
The .on event should support strings or ignore the data.

**Device details:**
 - Package Version 0.1.11

**Relevant Logs**

**Comment by tiholic** [comment]
@daniwaxman it will take some time for me to develop this, if you can develop the same, request you to create a PR

**Comment by tiholic** [comment]
@daniwaxman upgrade to 0.3.0 or higher and try

**Comment by daniwaxman** [comment]
Looks to b working now

Thanks!

**Comment by lmr520** [comment]
current version is support receive byte [] or other type data? usually  ours IM server send byte [] not json or string ,I have a big trouble for it
