### ISSUE TITLE
`adhara_socket_io` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

### ISSUE THREAD

**Issue by rajeshzmoke** [infitio/flutter_socket_io#40]
```
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.3 18D109, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.3)
[✓] IntelliJ IDEA Community Edition (version 2017.3.5)
[✓] VS Code (version 1.36.1)
[✓] Connected device (1 available)

• No issues found!
```
while running `pod install` i get this error

[!] Unable to determine Swift version for the following pods:

- `adhara_socket_io` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

**Comment by tiholic** [comment]
@rajeshzmoke do you see the same error with latest version `0.2.0` ?

**Comment by IChengLiWei** [comment]
i met the same error

**Comment by IChengLiWei** [comment]
i find casuse of the problem,and i only seted SWIFT_VERSION=4.2 in my target to solve it

**Comment by mps2209** [comment]
> i find casuse of the problem,and i only seted SWIFT_VERSION=4.2 in my target to solve it

could you explain how and where you did that? I am new to IOS developing

**Comment by althex2015** [comment]
i got same problem

**Comment by rajeshzmoke** [comment]
@tiholic  this happened after updating flutter to `Channel stable, v1.7.8+hotfix.3` , as some plugins were not compatible ..i reverted back to older version of flutter and that solved the issue

**Comment by althex2015** [comment]
> @tiholic this happened after updating flutter to `Channel stable, v1.7.8+hotfix.3` , as some plugins were not compatible ..i reverted back to older version of flutter and that solved the issue

how to revert it?

**Comment by IChengLiWei** [comment]
@mps2209 open your project in xcode ,and then find your target Build Setting.you can add user-defined setting that key=SWIFT_VERSION,value=4.2 or other version.
