### ISSUE TITLE
socket error: io.socket.engineio.client.EngineIOException: websocket error

### ISSUE THREAD

**Issue by youraleangseng** [infitio/flutter_socket_io#46]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Device details:**
 - Package Version [e.g. 22]

**Relevant Logs**
Add any relevant logs about the problem here.

**Comment by allansrc** [comment]
I'm going in the same error ... even when running the example project....

I have tried by this way:
make a function to call the events to init socket connection. call the function in a button.. but don't work at all.

` connectSocket() async {

   SocketIO socket = await SocketIOManager().createInstance(
   SocketOptions('http://127.0.0.1:7000')); 
   socket.onConnect((data) {
     print("connected...");
     print(data);
     socket.emit("message", ["Hello world!"]);
   });
   socket.on("news", (data) {
     //sample event
     print("news");
     print(data);
   });
  socket.connect();

 }`


the error::

E/Adhara:SocketIOPlugin(15905): java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
I/flutter (15905): io.socket.engineio.client.EngineIOException: websocket error

**Comment by sopheamen007** [comment]
same error here, how to solve it?

**Comment by masoumehAfra** [comment]
we have same error, how we can solve it ?

**Comment by allansrc** [comment]
I fix it changing the params to the same as my API:

for example:

```
`SocketIOManager manager = SocketIOManager();
    SocketIO socket = manager.createInstance('http://192.168.1.2:7000/');  // add SocketOptions(URI) inside of manager.createInstance()    
    socket.onConnect((data){
      print("connected...");
      print(data);
      socket.emit("message", ["Hello world!"]); // set "message to param listening on API socket.on"
    });
    socket.on("news", (data){   // hera is where you receive from `serve`
      print("news");
      print(data);
    });
    socket.connect()`
```
so, in my code it was like that:

```
SocketIOManager manager = SocketIOManager();
    SocketIO socket = manager.createInstance(SocketOption('http://10.0.0.2:7000/');  
    socket.onConnect((data){
      print("connected...");
      print(data);
      socket.emit("testSocket", ["Hello world!"]); 
    });
    socket.on("testSocket", (data){   
      print("testSocket");
      print(data);
    });
    socket.connect()`
```


p.s: in Android API 28 ^ the localhost don't work on 127.0.0.1. Use 10.0.0.2

**Comment by sopheamen007** [comment]
fixed by using ifconfig (Mac) in terminal and found ip : your wifi or internet wifi, and replace from 127.0.0.1 to your ip. thank you guys.

**Comment by rambozzang** [comment]
same error here, how to solve it? my server is aws.... dns or ip???

**Comment by tiholic** [comment]
@rambozzang you can use either DNS or IP

See https://github.com/infitio/flutter_socket_io/issues/21 discussion for more help regarding AWS socket connection

**Comment by tiholic** [comment]
@youraleangseng @masoumehAfra 
Refer to Point 3 in running the example. https://github.com/infitio/flutter_socket_io#running-example
Sample has to be followed when you are implementing this in your own application.

**Comment by kutigbolahan** [comment]
@allansrc i tried using another url with https and i keep getting this error: OpensslErr:Module:16(247:); file:external/boringssl/src/ssl/tls_record.cc ;Line:242;Function:tls_open_record

**Comment by askavinraja** [comment]
For those who get connection errors, follow these steps

1. add clear traffic permission in manifest

2. connect to your IP address of the system. (192.x.x.x)

3. try to downgrade the socket.io version in node server side.

4. and use the "flutter run command" instead of debugging. 

Peace!🤞

**Comment by ABOBAKAR-IT** [comment]
on remote server config the nginx

server  

{ 
       server_name backend.me; 

       location /{ 
             #  proxy_set_header X-Real-IP $remote_addr; 
               proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
               proxy_set_header Host $host; 
             #  proxy_set_header X-NginX-Proxy true; 
                proxy_pass http://localhost:4000/; 
                         proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
             #  proxy_redirect http://localhost:5000/ https://$server_name/;       
       } 
}
