### ISSUE TITLE
manager.clearInstance doesn't work

### ISSUE THREAD

**Issue by godlessturtle** [infitio/flutter_socket_io#49]
unable to disconnect either via kManager and manager. any problem?

```
  SocketIOManager manager = SocketIOManager();
    SocketIO socket = await manager.createInstance(SocketOptions('http://********/', enableLogging: false));

    global.kManager = manager;
    global.kSocket = socket;
```
**.
.
.**
``` await kManager.clearInstance(kSocket);```

**Comment by tiholic** [comment]
@godlessturtle are you facing this on iOS or Android?

**Comment by liuyun1014** [comment]
IOS is not reconnected, but it does not interrupt with the server

**Comment by godlessturtle** [comment]
@tiholic ios

**Comment by liuyun1014** [comment]
Has the problem been solved?
@godlessturtle

**Comment by tiholic** [comment]
@godlessturtle @liuyun1014 

Running the example works perfectly alright. See if this can help! Try upgrading to 0.3.4.

https://github.com/infitio/infitio.github.io/blob/master/adhara_socketio.mov

**Comment by godlessturtle** [comment]
i use another package, issue can be closed

**Comment by tiholic** [comment]
https://github.com/infitio/flutter_socket_io/issues/60
