### ISSUE TITLE
Add Authentication Headers

### ISSUE THREAD

**Issue by assemmarwan** [infitio/flutter_socket_io#50]
I am using a backend that has a socket.io server. To connect, I need to send authentication headers. There doesn't seem to be a way to set it.

How can I pass the authorization headers (Authorization: ${Token}).

**Comment by DanielR97** [comment]
Isn't this what you are trying to accomplish?

```dart
socket = await manager.createInstance(
  SocketOptions(
    socketURL,
    query: {
      'Authorization': ${Token},
    },
  ),
);
```

**Comment by tiholic** [comment]
@assemmarwan Socket headers wont work with websocket transport. They only work with polling transport.

You can use query params instead of customHeaders as @DanielR97 explained

**Comment by theochampion** [comment]
@tiholic How would you add the headers as there is no headers field in `SocketOption`?

**Comment by theochampion** [comment]
@tiholic I'm doing it like this at the moment but it doesn't seems to works as passports on the server looks for an actual cookie

```dart
      _conversationSocket = await manager.createInstance(SocketOptions(API_ROOT,
          transports: [
            Transports.POLLING
          ],
          query: {
            "conversation_id": widget.conversationID,
            "Cookie": cookies["session_cookie"]
          }));
```

**Comment by tiholic** [comment]
https://github.com/infitio/flutter_socket_io/issues/75
