### ISSUE TITLE
emit does not work on iOS

### ISSUE THREAD

**Issue by HenrikThien** [infitio/flutter_socket_io#53]
1) socket was created - working
2) connected to server - working
3) `socket.emit("start_session", xxxx...);` - does not work

The emit command does not work on iOS, on Android everything works fine..?

**Comment by Vardiak** [comment]
Does it make the app crash without any error ? Because that is what I'm facing.

**Comment by wapchief** [comment]
mark

**Comment by HenrikThien** [comment]
@Vardiak actually it doesn't do anything at all..Not even an exception

**Comment by milo2005** [comment]
The error is en AdharaSocket.swift in line 77, the reqId must be marked as an optional variable, example

let reqId: String? = arguments["reqId"] as? String

**Comment by qq326646683** [comment]
@milo2005 fixed this crash

**Comment by vuitv** [comment]
> The error is in AdharaSocket.swift file on line 77, the reqId must be marked as an optional variable, example
> 
> let reqId: String? = arguments["reqId"] as? String
Thanks you, it is work fine!

**Comment by tiholic** [comment]
@milo2005 @qq326646683 @vuitv this is fixed in https://github.com/infitio/flutter_socket_io/pull/57

Try upgrading to 0.3.3+1

**Comment by HenrikThien** [comment]
Still, I cannot emit messages to the socket.io server from iOS

`if (socket == null) return;
    socket.emit("start_session");`

in server

` socket.on("start_session")...`

But nothing happens with iOS. With Android everything works as expected

**Comment by tanujtak081986** [comment]
Any updates on this. I am facing the same issues. Nothing is emitted, and no errors logged.

**Comment by tiholic** [comment]
@HenrikThien @tanujtak081986 
Try upgrading to 0.3.4, and see if this helps.
https://github.com/infitio/infitio.github.io/blob/master/adhara_socketio.mov

**Comment by tanujtak081986** [comment]
Didn't get a chance to try this yet. Was travelling.
Will try this and get back to you if it works. 
Thanks.
