### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method newInstance on channel adhara_socket_io)

### ISSUE THREAD

**Issue by wapchief** [infitio/flutter_socket_io#54]
**Describe the bug**
use android studio run ios-Simulator on error：

```
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method newInstance on channel adhara_socket_io)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
<asynchronous suspension>
#1      SocketIOManager.createInstance (package:adhara_socket_io/manager.dart:16:32)
<asynchronous suspension>
#2      SocketUtils.socketTo (package:flutter_socket_io_demo/socket_utils.dart:24:28)
<asynchronous suspension>
#3      _MyHomePageState._incrementCounter (package:flutter_socket_io_demo/main.dart:58:17)
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:635:14)
#5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:711:32)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
#8      TapGestureRecognizer.acceptGesture (package:f<…>
```

use x-code run ios-Simulator on error：

```

fatal error: module map file '/Users/apple/Documents/project/public/flutter_socket_io_demo/build/ios/Debug-iphonesimulator/Socket.IO-Client-Swift/SocketIO.modulemap' not found
1 error generated.
```

**Device details:**
 - Device: [iPhoneXR]
 - OS: [e.g. iOS9]
 - Package Version [0.3.3]
 -  Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
 

**My Code**

```

class SocketUtils {
  static SocketIOManager manager;
  static SocketIO socket;

  static Future socketTo() async {
    manager =new SocketIOManager();
    //配置socket链接信息
    SocketOptions socketOptions = new SocketOptions(
      'https://ci.icxinli.com',
      query: {
        'token': testToken,
        'source': 'CONSULTANT',
      },
      transports: [Transports.WEB_SOCKET, Transports.POLLING],
      enableLogging: true,
    );
    socket = await manager.createInstance(socketOptions);
    socket.onConnect((res) {
//      socket.emit('rooms', []);
      print('onConnect--------' + res);
    });
    socket.on('rooms', (rooms) {
      print('rooms1111========' + rooms.toString());
      print('rooms2222========' + rooms[0].nickName);

      print('rooms3333========' + rooms.toString());

    });
    socket.connect();
  }
}
```

**Comment by tiholic** [comment]
@wapchief try full restart instead of hot-restart or hot-reload

**Comment by wapchief** [comment]
I ended up using v0.2.0

**Comment by oryjk** [comment]
hi, @wapchief, I use v0.2.0, but also has this issue, 
**my code**
`import 'package:adhara_socket_io/adhara_socket_io.dart';

Future main() async {
  SocketIO socket = await SocketIOManager().createInstance(
      SocketOptions('http://192.168.0.160/socket'));
  socket.onConnect((data) {
    print("connected...");
    print(data);
    socket.emit("message", ["Hello world!"]);
  });
  socket.on("news", (data) {
    //sample event
    print("news");
    print(data);
  });
  socket.connect();
}
`

**Comment by tiholic** [comment]
Performing a `flutter clean` and full restart will resolve this problem

**Comment by barees63** [comment]
I don't think this issue should be closed, using 0.4.2 I'm getting exactly the same error, flutter clean and restart does not help, I also tried removing it completely (and manually removing references from xcode) then reinstalled it and same error.

**Comment by tiholic** [comment]
@barees63 thanks for the details. Let me see what can be done with the inputs I have.

**Comment by feranmii** [comment]
@tiholic @barees63 I solved the issue by registering the plugin in the App Delegate.
First I added the path to `Runner-Bridging-Header.h`
```
#import "GeneratedPluginRegistrant.h"
#if __has_include(<adhara_socket_io/AdharaSocketIoPlugin.h>)
#import <adhara_socket_io/AdharaSocketIoPlugin.h>
#else
@import AdharaSocketIoPlugin;
#endif
```
Then I went ahead to add the line below to the `AppDelegate.swift` after `GeneratedPluginRegistrant.register(with: self)`

```AdharaSocketIoPlugin.register(with: self.registrar(forPlugin: "AdharaSocketIoPlugin")! )```

**Comment by pdivita** [comment]
> @tiholic @barees63 I solved the issue by registering the plugin in your project's App Delegate.
> First I added the path to `Runner-Bridging-Header.h`
> 
> ```
> #import "GeneratedPluginRegistrant.h"
> #if __has_include(<adhara_socket_io/AdharaSocketIoPlugin.h>)
> #import <adhara_socket_io/AdharaSocketIoPlugin.h>
> #else
> @import AdharaSocketIoPlugin;
> #endif
> ```
> 
> Then I went ahead to add this line to the `AppDelegate.swift` after `GeneratedPluginRegistrant.register(with: self)`
> 
> `AdharaSocketIoPlugin.register(with: self.registrar(forPlugin: "AdharaSocketIoPlugin")! )`

I'm using AppDelegate.m, I've added this line

`[AdharaSocketIoPlugin registerWithRegistrar:[registry registrarForPlugin:@"AdharaSocketIoPlugin"]];`

But I get this error:

```
AppDelegate.m:25:4: error: use of undeclared identifier 'AdharaSocketIoPlugin'
      [AdharaSocketIoPlugin registerWithRegistrar:[registry registrarForPlugin:@"AdharaSocketIoPlugin"]];
       ^
```

Any hint?

**Comment by tiholic** [comment]
@pdivita you missed the import statement. Import `AdharaSocketIoPlugin.h` into your AppDelegate

**Comment by pdivita** [comment]
Little update (I had problem only on iOS though):
0.4.1 works without any type of source modifications (.h / .m)
0.4.2: I've added your import, now I get:

```
AppDelegate.m:26:48: error: use of undeclared identifier 'registry'
      [AdharaSocketIoPlugin registerWithRegistrar:[registry registrarForPlugin:@"AdharaSocketIoPlugin"]];
```

My Flutter:
```
Flutter 1.17.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f7a6a7906b (2 weeks ago) • 2020-05-12 18:39:00 -0700
Engine • revision 6bc433c6b6
Tools • Dart 2.8.2
```

**Comment by tiholic** [comment]
@pdivita Pass `self` instead of `registry` as that is the registry required by registrar

did you try `0.4.1` with `flutter 1.17.1`? I'm suspecting this to be an issue with 1.17.1 as I too started facing this while working on further enhancements.

**Comment by pdivita** [comment]
I have 0.4.1 version of plugin and Flutter 1.17.1 on a production app available in the AppStore.
Adding self compiled correctly, but crashes at start.
```
Running pod install...                                              5,4s
Running Xcode build...                                                  
                                                   
 └─Compiling, linking and signing...                        49,1s
Xcode build done.                                           94,2s
Configuring the default Firebase app...
https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in_firebase_messaging
to ensure proper integration.
Configured the default Firebase app __FIRAPP_DEFAULT.
*** First throw call stack:
(
        0   CoreFoundation                      0x00007fff23e39f0e __exceptionPreprocess + 350
        1   libobjc.A.dylib                     0x00007fff50ad79b2 objc_exception_throw + 48
        2   CoreFoundation                      0x00007fff23e39c88 +[NSException raise:format:arguments:] + 88
        3   Foundation                          0x00007fff258a3cd2 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191
        4   Flutter                             0x000000010402e3a8 -[FlutterEngine registrarForPlugin:] + 320
        5   Runner                              0x00000001030f203d -[AppDelegate application:didFinishLaunchingWithOptions:] + 253
        6   UIKitCore                           0x00007fff48bbec2c -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 232
        7   UIKitCore                           0x00007fff48b<…>
This is taking longer than expected...

```
I'm reverting back to 0.4.1 because I need to update the app.
I'm available for testing though.

**Comment by tiholic** [comment]
@wapchief @oryjk @barees63 @feranmii @pdivita 

new release v1.0.0 aims to address all known connectivity issues. Please try and create new issues in case any.
Go through README for new updates.
