### ISSUE TITLE
Error on AdharaSocket.swift

### ISSUE THREAD

**Issue by milo2005** [infitio/flutter_socket_io#55]
**Describe the bug**
the reqId must be marked as an optional variable, on line 77

**Expected behavior**
let reqId: String? = arguments["reqId"] as? String

**Comment by wapchief** [comment]
mark,I also met this problem，Although I commented out the code, but does not solve the problem

**Comment by Saifallak** [comment]
having the same issue;


![3E316758-1F23-4790-B698-D95C5BD4CF09](https://user-images.githubusercontent.com/6053156/63218652-7d509e00-c15f-11e9-9942-30a7a1ea63ac.png)
