### ISSUE TITLE
Version 0.3.3 is not working onSending Data

### ISSUE THREAD

**Issue by breitembach** [infitio/flutter_socket_io#56]
Version 0.3.3 is not working onSending Data... is not working nothing...
just work in 0.2.0
i will stay 0.2.0 
Android

**Comment by tiholic** [comment]
@breitembach can you share any log by enabling logging! (pass `enableLogging:true` to socket options)

**Comment by breitembach** [comment]
I'm using, nothing fires when I send another device to send the information, everything works in version 0.2

**Comment by tiholic** [comment]
@breitembach Can you try out the example with latest code and let know if it works in your device?

**Comment by tiholic** [comment]
@breitembach v1.0.0 adds enhanced support with integration tests ensuring supported APIs.
You may try and re-open this issue if you face any difficulties.
