### ISSUE TITLE
HUA WEI mobil can't connect socketIO server.Are there anyone meet this question?

### ISSUE THREAD

**Issue by hzbsccd** [infitio/flutter_socket_io#59]
I can connect to the socketIO server with Simulator of Android or Iphone,or MI and VIVO (mobil with android system).But can not connect the server with the HUA WEI mobil(my phone version is Mate 9 Pro).
Are there anyone meet the same question?

（I use the adhara_socket_io version is 0.3.4）

**Comment by tiholic** [comment]
@hzbsccd Did you configure your server URL correctly? See the example video linked in Repo's README

**Comment by hzbsccd** [comment]
If the URL is wrong，other type real phone should can't connect with the server……，at the same time，I use android Simulator or Iphone Simulator，they can connect the release socketIO server，Except the HUA WEI mobil

**Comment by tiholic** [comment]
Is it android 9.0+?
In that case, try to add this
https://github.com/infitio/flutter_socket_io#android-support-for-sdk--27

**Comment by hzbsccd** [comment]
Thank you very much！I connect the server with your scheme.
this afternoon,I contract HUA WEI service，they can not provide any recommend，until I think here。Thank You!
