### ISSUE TITLE
manager.clearInstance() throws an PlatformException when multiple instances are cleared

### ISSUE THREAD

**Issue by rhessus** [infitio/flutter_socket_io#60]
**Describe the bug**
When i create multiple instances with manager.createInstance() and i clear them, in the same order, with manager.clearInstance(), the second throws an PlatformException.

**To Reproduce**
1. Create instance A and B (A index is 0 and B index is 1)
2. Clear instance A and after clear instance B
4. See PlatformException on manager.clearInstance() for instance B
5. The B instance is not cleared.

**Workaround**
1. Create instance A and B (A index is 0 and B index is 1)
2. Clear instance B and after clear instance A

**Expected behavior**
No exception should appear on this case.

**Device details:**
 - Device: Emulator and OP6T
 - OS: Android Pie
 - Package Version: 0.3.4

**Relevant Logs**
No log

**Solution**
In Swift and Java code, use Map instead of a List for the instances property in the manager class. Because, when an instance is cleared, the instances.count is decreased and the instance B with index 1 isn't found.

**Comment by tiholic** [comment]
@rhessus Can you try looking into the issue and raise a PR?

**Comment by rhessus** [comment]
i have submit a PR #63

**Comment by tiholic** [comment]
Released 0.3.5 to pub.dev

**Comment by tiholic** [comment]
Thanks to @rhessus
