### ISSUE TITLE
Implement disconnect method

### ISSUE THREAD

**Issue by rhessus** [infitio/flutter_socket_io#61]
Is it possible to implement the Dart disconnect method ? Java and Swift have already the code for that.

socket.dart:

  ///disconnect this socket to server
  disconnect() async {
    await _channel.invokeMethod("disconnect");
  }

Thanks in advance

**Comment by tiholic** [comment]
@rhessus disconnect is handled by SocketManager

refer the example code: https://github.com/infitio/flutter_socket_io/blob/master/example/lib/main.dart#L60
