### ISSUE TITLE
Sticky session

### ISSUE THREAD

**Issue by CalmAndCoDe** [infitio/flutter_socket_io#62]
hi, i used your socket io package but i want to know if your package support the session management it self?
because i configured the sticky session on my back-end for connecting to same instance for each request. when i try to connect it with my mobile app it keeps reconnecting? 
any help would be appreciated.
Thanks.

**Comment by tiholic** [comment]
@CalmAndCoDe can you share your Node.js code on how you configured Sticky Session in development?

**Comment by CalmAndCoDe** [comment]
@tiholic no im not using it in development, its on production and i want to develope an app for it, 
when i test it with another clients like js socket io client it works but when i use your this plugin in flutter it goes in reconnection loop.

**Comment by CalmAndCoDe** [comment]
thanks i solved it with updating to ^0.3.4  version and set the transport to the Transports.WEB_SOCKET.
