### ISSUE TITLE
Socket is not connecting after hot reload or full reload.

### ISSUE THREAD

**Issue by vimalmistry** [infitio/flutter_socket_io#64]
Socket is not connecting after state change hot reload or event full restart from vscode.
It is working fist time when we run it then after it is not connecting.

I am using Provider package for state management. Does any one have idea where to initialise socket.io to avoid multiple connect requests.
Thank you.

**Comment by Mohammad-ezzidden** [comment]
i have the same issue as well , the socket trigger the event but did't go inside the callback method.

**Comment by tiholic** [comment]
@vimalmistry @Mohammad-ezzidden 

v1.0.0 adds fix for this issue. Please try and re-open this issue in case you find any.
