### ISSUE TITLE
How can I make it work when the app is work on background

### ISSUE THREAD

**Issue by hzbsccd** [infitio/flutter_socket_io#68]
It can work when the App is work on foreground.Bun when the app is working on background,it can't get any message.How can I make it work as foreground?
Thank You.

**Comment by tiholic** [comment]
@hzbsccd you can use firebase messaging to send a push notification when the app is in background. Socket connection will not be active when the app is in background

**Comment by hzbsccd** [comment]
I find firebase messaging can push message to the all users of the App, but it can't push messages to the some users of the IM chat group.
