### ISSUE TITLE
Multiples connections on different host not working on Android

### ISSUE THREAD

**Issue by MorochoRochaDarwin** [infitio/flutter_socket_io#69]
**Describe the bug**
I have two socket-io host host1. After connect with the first socket-io host on  my home page next I am going to the Page2 I am trying to connect with the  host2 on iOS it works but on Android it doesn't work and the onError method never is called .

**Comment by tiholic** [comment]
@MorochoRochaDarwin glad that you could resolve the issue. If you can share your solution, it can help others who encounter the same error.
