### ISSUE TITLE
fatal error: 'adhara_socket_io/adhara_socket_io-Swift.h' file not found

### ISSUE THREAD

**Issue by masiJR** [infitio/flutter_socket_io#71]
**Describe the bug**
fatal error: 'adhara_socket_io/adhara_socket_io-Swift.h' file not found

**Comment by tiholic** [comment]
@KosalSK Please see if this helps resolve your issue https://github.com/infitio/flutter_socket_io#faqs

**Comment by githubsksk** [comment]
sir, i got the same problem.

**Comment by tiholic** [comment]
@githubsksk
Have you tried the example code?
Are you running from XCode?

**Comment by tiholic** [comment]
This could be a possible solution for this problem https://github.com/infitio/flutter_socket_io/issues/54#issuecomment-633992035
