### ISSUE TITLE
I/flutter (23174): io.socket.engineio.client.EngineIOException: websocket error

### ISSUE THREAD

**Issue by majdkz97** [infitio/flutter_socket_io#73]
I/flutter (23174): io.socket.engineio.client.EngineIOException: websocket error
I/flutter (23174): io.socket.engineio.client.EngineIOException: websocket error
I/flutter (23174): io.socket.engineio.client.EngineIOException: websocket error
I/flutter (23174): io.socket.engineio.client.EngineIOException: websocket error
I/flutter (23174): io.socket.engineio.client.EngineIOException: websocket error
I/flutter (23174): io.socket.engineio.client.EngineIOException: websocket error

**Comment by tiholic** [comment]
@majdkz97 the description is not very informative to comment on, however, you can try checking for connection to server from your mobile.

**Comment by DenisMrGnusa** [comment]
https://github.com/infitio/flutter_socket_io/issues/42#issuecomment-513459096
