### ISSUE TITLE
I can't find room implementation 

### ISSUE THREAD

**Issue by unknown1101** [infitio/flutter_socket_io#79]
As title i need to build chat app but i didn't find room in that driver

**Comment by mevlanaayas** [comment]
Hi @unknown1101, On client side do you really need room implementation? When I am doing room implementation for my chat app, I do it on server side (with Socket io). I use flutter_socket_io to send messages with room id or identifier of room and server side handle further steps. I am also watching this issue to see if there is a better way :)

**Comment by tiholic** [comment]
Thanks for the solution @mevlanaayas 
PR's are welcome if you are interested in implementing rooms in client side
