### ISSUE TITLE
no podspec found for 'adhara_socket_io'

### ISSUE THREAD

**Issue by byerman** [infitio/flutter_socket_io#80]
when i run flutter project in xcode 
get the error :
'adhara_socket_io/AdharaSocketIoPlugin.h' file not found
and i copy your podfile
run pod install in my project/ios
and get the error:
[!] No podspec found for `adhara_socket_io` in `.symlinks/plugins/adhara_socket_io/ios`
i can't find the resolution 
please help

**Comment by tiholic** [comment]
https://github.com/infitio/flutter_socket_io#adharasocketiopluginm29-fatal-error-adhara_socket_ioadhara_socket_io-swifth-file-not-found

See if this can help

**Comment by byerman** [comment]
> https://github.com/infitio/flutter_socket_io#adharasocketiopluginm29-fatal-error-adhara_socket_ioadhara_socket_io-swifth-file-not-found
> 
> @byerman看看这是否有帮助

it can help me ,thanks
