### ISSUE TITLE
Namespace options is not working for Android

### ISSUE THREAD

**Issue by vincentsong** [infitio/flutter_socket_io#82]
**Describe the bug**

Url: 'http://localhost:3000'
Options: namespace '/mobile'

Cannot connect to server from android app.

It's working as expect in iOS app.

**Have you tried reproducing the issue with example available in this repo?**
No

**Expected behavior**
Android app could connect to Server

**Comment by tiholic** [comment]
V1.0.0 ensures support for all supported API's under namespaces too with help of necessary integration tests.
You may upgrade and test.
