### ISSUE TITLE
如何在返回时断开socket , 返回时触发  disconnect(String identifier) async { ......  }

### ISSUE THREAD

**Issue by 718087538** [infitio/flutter_socket_io#85]
我需要在点击'返回'按钮时触发 disconnect(String identifier) async { ......  }方法断开连接,

但是拿不到这个方法,请问该怎么做.

使用 和 定义 '断开连接' 的方法不在同一个类.

**Comment by tiholic** [comment]
@718087538 use `clearInstance(sockerInstance)` to disconnect the instance
