### ISSUE TITLE
Disconnect

### ISSUE THREAD

**Issue by mrleesin** [infitio/flutter_socket_io#9]
How to disconnect with server?

SocketIOManager().clearInstance(socket);
doesnt work

**Comment by mrleesin** [comment]
Flutter

**Comment by tiholic** [comment]
@mrleesin  are you trying to disconnect in dispose method?

Is this something similar to https://github.com/infitio/flutter_socket_io/issues/6

**Comment by tiholic** [comment]
https://github.com/infitio/flutter_socket_io/issues/13
