### ISSUE TITLE
Can't connect to custom endpoint

### ISSUE THREAD

**Issue by Vardiak** [infitio/flutter_socket_io#94]
This not a typical use case for socket.io but I'm facing an issue with something that works perfectly fine one the web.
I currently run multiple socket.io servers with different endpoints managed by a proxy. When on the home page, I connect to the `/` namespace with `http://example/socket.io` as a path.
Sometimes, I need to connect to another Node.js running on the `/game` endpoint with an ID as a namespace, so I simply connect to the `/id` namespace with `http://example/game/socket.io` as a path.

This works well on the web but when I try to connect using flutter_socket_io it seems that I connect to my main server and get an "invalid namespace" error.

Do you have an idea on how to fix this ?

**Comment by Vardiak** [comment]
After doing some research, I found that the URL is not equivalent to the path we use in socket.io-client (web version). We have to specify the path for socket.io-java and socket.io-swift but this is not handled in flutter_socket_io.
I can try to do a pull request to support this for android, but I'm not sure I will be able for iOS.

**Comment by Vardiak** [comment]
I submited a pull request to fix this issue #95

**Comment by tiholic** [comment]
Glad you discovered and fixed it. Thanks for the contribution. I will release it to pub in couple of days.
