### ISSUE TITLE
On all devices "websocket error"

### ISSUE THREAD

**Issue by Fatalius** [infitio/flutter_socket_io#99]
First I added flutter_socket_io in to my project, and I never get connect to my socket.io server
Then launched an example from the repository and when I tap on any of the types of connections I get an error(device and emulator):

I / flutter (9586): io.socket.engineio.client.EngineIOException: websocket error
I / flutter (9586): io.socket.engineio.client.EngineIOException: websocket error
I / flutter (9586): io.socket.engineio.client.EngineIOException: websocket error
I / flutter (9586): io.socket.engineio.client.EngineIOException: websocket error
...

<img width="319" alt="Снимок экрана 2019-10-31 в 22 03 05" src="https://user-images.githubusercontent.com/6808203/67978067-523bfd80-fc2a-11e9-88ab-e09b7a02bc32.png">

thanks...

**Comment by aslamanver** [comment]
This is because you might use the IP address inside the emulator, please try to start from a real device.

**Comment by Fatalius** [comment]
on a real device the same, see on subject "On all devices "websocket error""

**Comment by DenisMrGnusa** [comment]
maybe,,
https://github.com/infitio/flutter_socket_io/issues/42#issuecomment-513459096

**Comment by tiholic** [comment]
Hope this issue is resolved @Fatalius 

Closing this. Feel free to re-open if required.
